---
title: ""
author: ""
date: ""
output: html_document
---

Hello.

You are currently enrolled in **MTH107 -- Statistical Concepts and Analyses**. Below are several announcements regarding this course.

* A website with all course materials is at http://derekogle.com/NCMTH107/. Please note that I host the class website on my personal webpage and not on the Northland portal. Thus, please use the address in the first sentence, rather than going through MyNorthland.
* There is no commercial textbook for this course. Rather, I will provide videos and PDFs on the course website for each module of material. Please see [this FAQ](http://derekogle.com/NCMTH107/resources/FAQ/FAQs/videos) about watching the videos.
* All necessary software for the course is available on public computers in Northland's computer labs. However, if you want to use your own personal computer, you will need to install the freely available R program, RStudio program, and necessary packages as described in the first three links under the "Software Installation Links" section on [the Resources page on the course website](http://derekogle.com/NCMTH107/resources#software-installation-links). Let me know if you need assistance with these installations.

**Finally, you should prepare for the first day of class by**

* Reading the syllabus (see the ["syllabus" tab](http://derekogle.com/NCMTH107/resources/Syllabus-Current) at the top of the course website). We will not discuss the syllabus in detail, but you are responsible for all the material therein.
* Prepare **hand**-written answers to the questions in the preparation guide for the "Why Statistics is Important" module (use the "modules" tab on the website, then select the first module). This will require you to do the reading and watch the videos listed under the "Preparation for Class" section on that page. You will be responsible for this material on the first day of class (**and may be asked to hand in your hand-written answers to the questions in the preparation guide**).

Please let me know (dogle@northland.edu) if you have any questions.
