---
title: "Exam 2 Analysis"
output: pdf_document
---

```{r echo=FALSE, message=FALSE, results='hide'}
library(NCStats)
library(readxl)
library(dplyr)
library(knitr)
source("../../rhelpers/knitr_setup.R")
setwd("C:/aaaWork/Web/GitHub/NCMTH107/Year_Specific/F16")
d1 <- read_excel("MTH107_Grades_F16.xlsx",sheet="MT1",skip=2) %>%
  filterD(Total>0)
str(d1)
d2 <- read_excel("MTH107_Grades_F16.xlsx",sheet="MT2",skip=2)
d2 <- d2[,-which(names(d2)=="")]
d2 <- filterD(d2,Total>0)
str(d2)
d3 <- read_excel("MTH107_Grades_F16.xlsx",sheet="Overall",skip=2)
d3 <- Subset(d3,!is.na(MT1) & !is.na(MT2) & MT2>0)
d3 <- d3[,-which(names(d3) %in% c("SawTutor","SawProf","mt1","mt2","mt4","%",""))]
str(d3)
```

----

# Overall Score

```{r echo=FALSE, fig.width=5, fig.height=4, par1=TRUE}
hist(~Perc,data=d2,xlab="Proportional Score",w=0.05,ylim=c(0,8))
abline(v=c(0.6,0.7,0.8,0.9),lwd=2,col="red",lty=2)
text(c(0.5,0.65,0.75,0.85,0.95),7.75,c("F","D","C","B","A"))
Summarize(~Perc,data=d2,digits=2)
```

----

# Relationship with Overall Score and Quiz/HW Scores

```{r echo=FALSE, fig.width=3, fig.height=3, par1=TRUE}
plot(MT2~Quiz,data=d3,ylab="Second Exam Score",xlab="Quiz Scores Prior to Second Exam",pch=21,bg=col2rgbt("black",0.25))
plot(MT2~HW,data=d3,ylab="Second Exam Score",xlab="Homework Scores Prior to Second Exam",pch=21,bg=col2rgbt("black",0.25))
plot(MT2~MT1,data=d3,ylab="Second Exam Score",xlab="First Exam Score",
     pch=21,bg=col2rgbt("black",0.25))
abline(a=0,b=1,col=col2rgbt("red",1/2))
```

----

# Individual proportions

```{r echo=FALSE}
tmp <- select(d2,starts_with("p."))
lapply(as.list(tmp),Summarize,digits=2)
```

