---
title: "First Day Preparations"
author: "Dr. Derek H. Ogle"
date: "January 3, 2017"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You are currently enrolled in **MTH107 -- Statistical Concepts and Analyses**.  Below are several announcements regarding this course.

* A website with all of the course materials is at http://derekogle.com/NCMTH107/. 
* There is no commercial textbook for this course.  Rather, I will provide a PDF on the course website (see the ["book" tab](http://derekogle.com/NCMTH107/book/) at the top).  Alternatively, I will make arrangements on the first day of class to have a hardcopy produced if you would prefer that.  The price of the hardcopy is approx. $25 (I will have a final price on the first day of the course) and covers the costs of photocopying and binding.  Purchasing a hardcopy from me is completely optional.  However, you may want to spend some time before the first day of the class looking at the PDF to see if that option is going to work well for you or not.
* You may want to install some software on your personal computer (which you may use during class if you so choose).  Directions for installing R, RStudio, and necessary packages are at the bottom of [the Resources page on the course website](http://derekogle.com/NCMTH107/resources/).  Let me know if you need assistance installing these softwares.
* You should prepare for the first day of class by reading the syllabus (see the ["syllabus" tab](http://derekogle.com/NCMTH107/resources/Syllabus-Current) at the top of the course website).
* You may also want to prepare for the second day of class by watching the videos for the "Why Statistics is Important" module (use the ["modules" tab on the website, then select the first module](http://derekogle.com/NCMTH107/modules/Why_Statistics_is_Important/), and then select and watch the four videos posted there).

Please let me know if you have any questions.
