<<echo=FALSE, cache=FALSE, results='hide'>>=
set_parent('IntroStats.Rnw')
@

\chapter{Foundational Definitions} \label{chap:FoundationalDefinitions}
\begin{ChapObj}{\boxwidth}
  \textbf{Objectives:}
  \begin{Enumerate}
    \item Describe what an individual is.
    \item Describe what a population and a sample are and how they differ.
    \item Describe what a parameter and a statistic are and how they differ.
    \item Describe how a population, parameter, sample, and statistic are related.
    \item Identify the individual, variable(s), population, parameter(s), sample, and statistic(s) (IVPPSS) in a given situation.
    \item Identify variable types in context.
  \end{Enumerate}
\end{ChapObj}

\minitoc
\newpage

\lettrine{S}{tatistical inference is the process} of forming conclusions about the unknown parameters of a population by computing statistics from the individuals in a sample.\index{Inference!Definition}  As you can imagine from this definition, it is important that you understand the difference between a population and a sample and a parameter and a statistic before you can understand and appreciate the process of making statistical inferences.  Before identifying these items, the individual and variable(s) of interest must also be identified.  Understanding and identifying these six items is the focus of this module.  Formal methods of inference are discussed beginning with \modref{chap:ProbIntro}.

\defn{Inference}{The process of forming conclusions about the unknown parameters of a population by computing statistics from the individuals in a sample.}

The following hypothetical example is used throughout this module.  Assume that interest is in determining the mean (or average) length of the 1015 fish in Square Lake \figrefp{fig:SquareLakePopn}. In ``real life'' you would not know how many fish are in this lake.  However, for the purpose of illustrating important concepts in this module, it is assumed that all information for all 1015 fish in this lake is known.

<<SquareLakePopn, echo=FALSE, fig.cap="Schematic representation of individual fish (i.e., dots; \\textbf{Left}) and histogram (\\textbf{Right}) of the total length of the 1015 fish in Square Lake.">>=
data(SquareLakePopn)
SL <- SquareLakePopn
SL$i<-seq(1:1015)
SL$x<-runif(1015)
SL$y<-runif(1015)
plot(SL$x,SL$y,pch=16,xlab="",ylab="",xaxt="n",yaxt="n")
hist(~tl,data=SL,xlab="Total Length",ylab="Frequency of Fish")
@

\vspace{-24pt}
\section{Definitions} \label{sect:IVPPSS}
\vspace{-12pt}
The \textbf{individual} in a statistical analysis is one of the ``items'' to be examined by the researcher.\index{Individual, Definition}  Sometimes the individual is a person, but it may be an animal, a piece of wood, a site or location, a particular time, or an event.  It is extremely important that you don't always visualize a person when you use the word individual in a statistical context.  Synonyms for individual are unit, experimental unit (usually used in experiments), sampling unit (usually used in observational studies), case, and subject (usually used in studies involving humans).  The individual of interest in the Square Lake example is an individual fish, because the researcher will collect a set of fish and examine each fish individually.

\defn{Individual}{One of the items examined by the researcher.}

\vspace{-12pt}
\warn{An individual is not necessarily a person.}

The \textbf{variable} is the characteristic of interest recorded about each individual.\index{Variable!Definition} The variable of interest in the Square Lake example is the length of each fish. Note that in most ``real life'' studies the researcher will record more than one variable.  For this example, the researcher may also record the fish's weight, sex, and age.  Studies with one variable are called univariate studies, studies with two variables are bivariate studies, and studies with more than two variables are called multivariate studies.

\defn{Variable}{The characteristic of interest recorded about each individual.}

A \textbf{population} is ALL individuals of interest.\index{Population} In the Square Lake example, the population is all 1015 fish in the lake.  The population should be defined as thoroughly as possible including qualifiers as necessary.  This example is simple because Square Lake is so well defined; however, as you will see in the review exercises, the population is often only well-defined by your choice of descriptors.

\defn{Population}{ALL individuals of interest.}

A \textbf{parameter} is a summary computed from ALL individuals in a population.\index{Parameter!Definition}  The term for the particular summary is usually preceded by the word ``population.''  Parameters are ultimately what is of interest because interest is in all individuals in the population.  However, in practice, parameters cannot be computed because the entire population cannot be ``seen.''  In this hypothetical example, the parameters can be computed because all 1015 fish are accessible.  In this example, the researchers were interested in the population mean length of all fish in Square Lake, which is \Sexpr{round(mean(SL$tl),2)} mm \tabrefp{tab:SquareLakePopn}.\footnote{We will discuss how to compute and interpret each of these values in later modules.}

<<SquareLakePopnTbl, results="asis", echo=FALSE >>=
slstat <- Summarize(SL$tl,digits=2)
slstat1 <- matrix(slstat,nrow=1)
colnames(slstat1) <- names(slstat)
sl.x <- xtable(slstat1,align=rep("c",ncol(slstat1)+1),digits=c(0,0,2,2,0,0,0,0,0),caption="Parameters for the total length of ALL 1015 fish in the Square Lake population.","tab:SquareLakePopn")
print(sl.x,caption.placement="top",hline.after=c(0,nrow(sl.x)),include.rownames=FALSE)
@

\defn{Parameter}{A summary of ALL individuals in a population.}

\vspace{-12pt}
\warn{Populations and parameters can generally not be ``seen.''}

The entire population cannot be ``seen'' in real life.  Thus, a subset of the population is usually examined to learn something about the population.  This subset is called a \textbf{sample}.\index{Sample!Definition}  The red dots in \figref{fig:SquareLakeSample1} represent a random sample of n=50 fish from Square Lake (note that the sample size is usually denoted by n).

<<SquareLakeSample1, echo=FALSE, fig.cap="Schematic representation (\\textbf{Left}) of a sample of 50 fish (i.e., red dots) from Square Lake and histogram (\\textbf{Right}) of the total length of the 50 fish in this sample.">>=
set.seed(1)
SL1 <- srsdf(SL,n=50)
plot(y~x,data=SL,pch=19,xlab="",ylab="",xaxt="n",yaxt="n")
points(y~x,data=SL1,pch=19,col="red",cex=1.25)
hist(~tl,data=SL1,xlab="Total Length",ylab="Frequency of Fish")
@

\defn{Sample}{A subset of the population examined by a researcher.}

Summaries computed from individuals in a sample are called \textbf{statistics}.\index{Statistic!Definition}  Specific names of statistics are preceded by ``sample.''  The statistic of interest is always the same as the parameter of interest; i.e., the statistic describes the sample in the same way that the parameter describes the population.  For example, if interest is in the population mean, then the sample mean would be computed.

Some statistics computed from the sample from Square Lake are shown in \tabref{tab:SquareLakeSample1} and \figref{fig:SquareLakeSample1}.  The sample mean of \Sexpr{round(mean(SL1$tl),2)} mm is the best ``guess'' at the population mean.  Not surprisingly from the discussion in \modref{chap:WhyStatsImportant}, the sample mean does not perfectly equal the population mean.

<<SquareLakeSample1s, results="asis", echo=FALSE >>=
slstat <- Summarize(SL1$tl,digits=2)
slstat1 <- matrix(slstat,nrow=1)
colnames(slstat1) <- names(slstat)
sl1.x <- xtable(slstat1,align=rep("c",ncol(slstat1)+1),digits=c(0,0,2,2,0,0,0,0,0),caption="Summary statistics for the total length of a sample of 50 fish from the Square Lake population.","tab:SquareLakeSample1")
print(sl1.x,caption.placement="top",hline.after=c(0,nrow(sl1.x)),include.rownames=FALSE)
@

\defn{Statistic}{A summary of all individuals in a sample.}


\section{Performing an IVPPSS}
\vspace{-12pt}
In each statistical analysis it is important that you determine the Individual, Variable, Population, Parameter, Sample, and Statistic (\textbf{IVPPSS}). First, determine what items you are actually going to look at; those are your individuals.  Second, what are you going to record when you look at an individual; that is the variable.  Third, the population is simply ALL of the individuals.  Fourth, the parameter is a summary (e.g., mean or proportion) of the variable recorded from ALL of the individuals in the population.\footnote{Again, parameters generally cannot be computed because all of the individuals in the population can not be seen.  Thus, the parameter is largely conceptual.}  Fifth, we usually cannot see all of the individuals in the population so only a few are examined; those few are the sample.  Finally, the summary of the individuals in the sample is the statistic.

When performing an IVPPSS, keep in mind that parameters describe populations (note that they both start with ``p'') and statistics describe samples (note that they both start with ``s'').  This can also be looked at from another perspective.  A sample is an estimate of the population and a statistic is an estimate of a parameter.  Thus, the statistic has to be the same summary (mean or proportion) of the sample as the parameter is of the population.

The IVPPSS process is illustrated for the following situation:
\vspace{-12pt}
\begin{quote}
\textit{A University of New Hampshire graduate student (and Northland College alum) investigated habitat utilization by New England (Sylvilagus transitionalis) and Eastern (Sylvilagus floridanus) cottontail rabbits in eastern Maine in 2007.  In a preliminary portion of his research he determined the proportion of ``rabbit patches'' that were inhabited by New England cottontails.  He examined 70 ``patches'' and found that 53 showed evidence of inhabitance by New England cottontails.}
\end{quote}

\begin{Itemize}
  \item An individual is a rabbit patch in eastern Maine in 2007 (i.e., a rabbit patch is the ``item'' being sampled and examined).
  \item The variable is ``evidence for New England cottontails or not (yes or no)'' (i.e., the characteristic of each rabbit patch that was recorded).
  \item The population is ALL rabbit patches in eastern Maine in 2007.
  \item The parameter is the proportion of ALL rabbit patches in eastern Maine in 2007 that showed evidence for New England cottontails.\footnote{Note that this population and parameter cannot actually be calculated but it is what the researcher wants to know.}
  \item The sample is the 70 rabbit patches from eastern Maine in 2007 that were actually examined by the researcher.
  \item The statistic is the proportion of the 70 rabbit patches from eastern Maine in 2007 actually examined that showed evidence for New England cottontails. [In this case, the statistic would be 53/70 or \Sexpr{formatC(53/70,format="f",digits=3)}.]
\end{Itemize}

In some situations it may be easier to identifying the sample first.  From this, and through the realization that a sample is always ``of the individuals'', it may be easier to identify the individual.  This process is illustrated in the following example, with the items listed in the order identified rather than in the traditional IVPPSS order.

\begin{quote}
\textit{The Duluth, MN Touristry Board is interested in the average number of raptors seen per year at Hawk Ridge.\footnote{Information about Hawk Ridge is found \href{http://www.hawkridge.org/}{here}.}  To determine this value, they collected the total number of raptors seen in a sample of years from 1971-2003.}
\end{quote}

\begin{Itemize}
  \item The sample is the 32 years between 1971-2003 at Hawk Ridge.
  \item An individual is a year (because a ``sample of \emph{years}'' was taken) at Hawk Ridge.
  \item The variable recorded was the number of raptors seen in one year at Hawk Ridge.
  \item The population is ALL years at Hawk Ridge(this is a bit ambiguous but may be thought of as all years that Hawk Ridge has existed).
  \item The parameter is the average number of raptors seen per year in ALL years at Hawk Ridge.
  \item The statistic is the average number of raptors seen in the 1971-2003 sample of years at Hawk Ridge.
\end{Itemize}

\begin{exsection}
  \item \label{revex:IVPPSSDad}My Dad owns 60 acres of timber (mostly Oak, Walnut, and Poplar) in Iowa.  He wants to measure the mean diameter-at-breast-height (DBH) of the oak trees on his property.  He measures the DBH of 75 randomly selected oak trees.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSDad}
  \item \label{revex:IVPPSSFishStore}I have a friend who wants to start a (fishing) bait store on the West end of Ashland.  He wants to determine what proportion of Ashland residents who currently use the East end bait store would use a store in the West end if one existed.  He sends out 5000 questionnaires and receives 2378 back from patrons of the East end store.   Use this information to perform an IVPPSS.  \ansref{ans:IVPPSSFishStore}
  \item \label{revex:IVPPSSNBA}I'm interested in developing a model to predict how many points an NBA starting basketball player scores. Therefore, I want to determine the relationship between points scored and height, speed (in the 40-yard dash), position, and minutes played. To identify this relationship I gather these data from 100 NBA starting basketball players.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSNBA}
  \item \label{revex:IVPPSSClinton}Pollsters wanted to determine the proportion of registered voters who approved of President Clinton's performance.  They called 5000 randomly selected registered voters and ask 4123 of those (the rest weren't home, didn't answer, or hung up) ``Do you approve of Pres. Clinton's performance?''  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSClinton}
  \item \label{revex:IVPPSSGoslings}You Might Be Interested To Know (YMBITK), the average level of mercury in newly-hatched goslings in the upper Midwest (MI, MN, ND, SD, WI). You obtained 20 goslings from resource agencies in each state.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSGoslings}
  \item \label{revex:IVPPSSNClead}YMBITK, the proportion of NC students that think NC can become ``the nation's leading environmental liberal arts college'' in the next decade. You polled 124 students.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSNClead}
  \item \label{revex:IVPPSSStudy}YMBITK, the relationship between hours studied and GPA of students in the UW system (excluding UW-Madison). You interviewed 250 students from throughout the system.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSStudy}
  \item \label{revex:IVPPSSCoach}YMBITK, the average difference in salaries between the head coaches of men's and head coaches of women's basketball teams at Division I schools. You interviewed 73 head-coach pairs.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSCoach}
  \item \label{revex:IVPPSSBioGrads}YMBITK, the proportion of graduates from small private schools, who majored in Biology and who have been out of school for at least 5 years, that feel that statistics is an ``important'' course. You interviewed 1023 people.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSBioGrads}
  \item \label{revex:IVPPSSBaikal}Scientist in Chivyrkui Bay on Lake Baikal \citep{OwensPronin2000} were interested, among other things, in determining the mean age of pike (\textit{Esox lucius}) in the bay. They collected scales from 30 fish using gill nets and angling methods. Use this information to perform an IVPPSS. \ansref{ans:IVPPSSBaikal}
  \item \label{revex:IVPPSSRuffe}The Eurasian ruffe is an exotic species of fish that is causing some alarm in fisheries biologists in the Great Lakes area \citep{Maniaketal2000}. A few of these biologists tested to see if a certain pheromone released by injured ruffe would repel other ruffe.  If so, natural, or possibly synthetic, versions of this pheromone could be used to distract ruffe from areas in which they are causing damage. In their experiment, they observed ruffe held in aquaria divided into four sections.  They recorded what proportion of 24 randomly-selected ruffe caught in the St. Louis River Harbor, and then held in the aquaria, left a section when the chemical was added to that section.  Use this information to perform an IVPPSS. \ansref{ans:IVPPSSRuffe}
\end{exsection}


\subsection{Sampling Variability (Revisited)}
It is instructive to once again (see \modref{chap:WhyStatsImportant}) consider how statistics differ among samples.  \tabref{tab:SquareLakeSample234} and \figref{fig:SquareLakeSample234} show results from three more samples of n=50 fish from the Square Lake population.  The means from all four samples (including the sample in \tabref{tab:SquareLakeSample1} and \figref{fig:SquareLakeSample1}) were quite different from the known population mean of 98.06 mm.  Similarly, all four histograms were similar in appearance but were slightly different in actual values. These results illustrate that a statistic (or sample) will only approximate the parameter (or population) and that statistics vary among samples.  This \textbf{sampling variability} is one of the most important concepts in statistics and will be discussed in great detail beginning in \modref{chap:SamplingDist}.\index{Sampling Variability!Definition}

<<SquareLakeSample234, echo=FALSE, fig.width=5, fig.height=7.5, out.width='.7\\linewidth', fig.cap="Schematic representation (\\textbf{Left}) of three samples of 50 fish (i.e., red dots) from Square Lake and histograms (\\textbf{Right}) of the total length of the 50 fish in each sample.">>=
set.seed(2); SL2 <- SL[sample(SL$i,50),]
set.seed(3); SL3 <- SL[sample(SL$i,50),]
set.seed(4); SL4 <- SL[sample(SL$i,50),]
par(mar=c(3.5,3.5,0.5,0.5),mgp=c(2.1,0.4,0),mfcol=c(3,2))
plot(SL$x,SL$y,pch=16,xlab="",ylab="",xaxt="n",yaxt="n")
points(SL2$x,SL2$y,pch=16,col="red",cex=1.25)
plot(SL$x,SL$y,pch=16,xlab="",ylab="",xaxt="n",yaxt="n")
points(SL3$x,SL3$y,pch=16,col="red",cex=1.25)
plot(SL$x,SL$y,pch=16,xlab="",ylab="",xaxt="n",yaxt="n")
points(SL4$x,SL4$y,pch=16,col="red",cex=1.25)
hist(~tl,data=SL2,xlab="Total Length",ylab="Frequency of Fish")
hist(~tl,data=SL3,xlab="Total Length",ylab="Frequency of Fish")
hist(~tl,data=SL4,xlab="Total Length",ylab="Frequency of Fish")
@

<<SquareLakeSample234s, results="asis", echo=FALSE >>=
SL2.sum <- Summarize(SL2$tl,digits=2)
SL3.sum <- Summarize(SL3$tl,digits=2)
SL4.sum <- Summarize(SL4$tl,digits=2)
SL234.sum <- rbind(SL2.sum,SL3.sum,SL4.sum)
rownames(SL234.sum) <- 2:4
SL234.x <- xtable(SL234.sum,align=rep("c",ncol(slstat1)+1),digits=c(0,0,2,2,0,0,0,0,0),caption="Summary statistics for the total length in three samples of 50 fish from the Square Lake population.","tab:SquareLakeSample234")
print(SL234.x,caption.placement="top",hline.after=c(0,nrow(SL234.x)),include.rownames=FALSE,table.placement="htbp")
@

\defn{Sampling Variability}{The realization that no two samples are exactly alike. Thus, statistics computed from different samples will likely vary.}

This example also illustrates that parameters are fixed values because populations don't change.  If a population does change, then it is considered to be a different population.  In the Square Lake example, if a fish is removed from the lake, then the lake would then be considered a different population of fish.  Statistics, on the other hand, vary depending on the sample because each sample consists of different individuals that vary (i.e., sampling variability exists because natural variability exists).

\warn{Parameters are fixed in value, while statistics vary in value.}


\clearpage
\section{Variable Types}\label{sect:VarTypes}
The type of statistic that can be calculated is dictated by the type of variable to be analyzed.  For example, a sample mean (or average) can only be calculated for a quantitative variable (defined below).  Thus, the type of that variable should be identifie immediately after performing an IVPPSS.

\subsection{Variable Definitions}
There are two main groups of variable types -- quantitative and categorical \figrefp{fig:VarTypes}.  \textbf{Quantitative} variables are variables with numerical values for which it makes sense to do arithmetic operations (like adding or averaging).\index{Quantitative Variable}  Synonyms for quantitative are measurement or numerical.  \textbf{Categorical} variables are variables that record to which group or category an individual belongs.\index{Categorical Variable}  Synonyms for categorical are qualitative or attribute.  Within each main type of variable are two subgroups \figrefp{fig:VarTypes}.

<<VarTypes, echo=FALSE, fig.width=5, fig.height=2.5, out.width='.5\\linewidth', fig.cap="Schematic representation of the four types of variables.">>=
par(mar=c(0,0,0,0),cex=1.5)
plot(NA,xlim=c(0,5),ylim=c(-1.,1.),xaxt="n",yaxt="n",xlab="",ylab="",bty="n")
text(-0.25,0,"Variable",pos=4)
text(1.3,-0.65,"Quantitative",pos=4,col="blue")
text(3.6,-0.25,"Continuous",pos=4,col="blue")
text(3.6,-0.95,"Discrete",pos=4,col="blue")
arrows(0.95,0,1.45,-0.55,lwd=3,length=0.1,col="blue")
arrows(2.95,-0.65,3.7,-0.25,lwd=3,length=0.1,col="blue")
arrows(2.95,-0.65,3.7,-0.95,lwd=3,length=0.1,col="blue")

text(1.3,0.65,"Categorical",pos=4,col="red")
text(3.6,0.95,"Nominal",pos=4,col="red")
text(3.6,0.25,"Ordinal",pos=4,col="red")
arrows(0.95,0,1.45,0.55,lwd=3,length=0.1,col="red")
arrows(2.9,0.65,3.7,0.95,lwd=3,length=0.1,col="red")
arrows(2.9,0.65,3.7,0.25,lwd=3,length=0.1,col="red")
@
\vspace{9pt} % added because of paragraph compressions following R code

The two types of quantitative variables are continuous and discrete variables.  \textbf{Continuous} variables are quantitative variables that have an uncountable number of values.\index{Continuous Variable}  In other words, a potential value \textsc{does} exist between every pair of values of a continuous variable.  \textbf{Discrete} variables are quantitative variables that have a countable number of values.\index{Discrete Variable}  Stated differently, a potential value \textsc{does not} exist between every pair of values of a discrete variable.  Typically, but not always, discrete variables are counts of items.

Continuous and discrete variables are easily distinguished by determining if it is possible for a value to exist between every two values of the variable.  For example, can there be between 2 and 3 ducks on a pond?  No!  Thus, the number of ducks is a discrete variable.  Alternatively, can a duck weigh between 2 and 3 kg?  Yes!  Can it weigh between 2 and 2.1 kg?  Yes!  Can it weigh between 2 and 2.01 kg?  Yes!  You can see that this line of questions could continue forever; thus, duck weight is a continuous variable.

\defn{Discrete Variable}{A quantitative variable that can assume a countable number of values.}

\vspace{-12pt}
\defn{Continuous Variable}{A quantitative variable that can assume an uncountable number of values.}

\vspace{-12pt}
\warn{A quantitative variable is continuous if a possible value exists between every two values of the variable; otherwise, it is discrete.}

The two types of categorical variables are ordinal and nominal.  \textbf{Ordinal} variables are categorical variables where a natural order or ranking exists among the categories.\index{Ordinal Variable}  \textbf{Nominal} variables are categorical variables where no order or ranking exists among the categories.\index{Nominal Variable}

Ordinal and nominal variables are easily distinguished by determining if the order of the categories matters.  For example, suppose that a researcher recorded a subjective measure of condition (i.e., poor, average, excellent) and the species of each duck.  Order matters with the condition variable -- i.e., condition improves from the first (poor) to the last category (excellent) -- and some reorderings of the categories would not make sense -- i.e., average, poor, excellent does not make sense.  Thus, condition is an ordinal variable.  In contrast, species (e.g., mallard, redhead, canvasback, and wood duck) is a nominal variable because there is no inherent order among the categories (i.e., any reordering of the categories also ``makes sense'').

\defn{Ordinal Variable}{A categorical variable for which a natural order exists among the categories.}

\vspace{-12pt}
\defn{Nominal Variable}{A categorical variable for which a natural order DOES NOT exist among the categories.}

\vspace{-12pt}
\warn{Remember that \textbf{ord}inal means that an \textbf{ord}er among the categories exists (note ``ord'' in both ordinal and order).}

The following are some issues to consider when identifying the type of a variable:
\begin{Enumerate}
  \item The categories of a categorical variable are sometimes labeled with numbers. For example, 1=``Poor'', 3=``Fair'', and 5=``Good''.  Don't let this fool you into calling the variable quantitative.
  \item Rankings, ratings, and preferences are ordinal (categorical) variables.
  \item Counts of numbers are discrete (quantitative) variables.
  \item Measurements are typically continuous (quantitative) variables.
  \item It does not matter how precisely quantiative variables are recorded when deciding if the variable is continuous or discrete. For example, the weight of the duck might have been recorded to the nearest kg. However, this was just a choice that was made, the actual values can be continuously finer than kg and, thus, weight is a continuous variable.
  \item Categorical variables that consist of only two levels or categories will be labeled as a nominal variable (because any order of the groups makes sense).  This type of variable is also often called ``binomial.''.
  \item Do not confuse ``what type of variable'' (answer is one of ``continuous'', ``discrete'', ``nominal'', or ``ordinal'')  with ``what type of variability'' (answer is ``natural'' or ``sampling'') questions.
\end{Enumerate}

\warn{``What type of variable is ...?'' is a different question than ``what type of variability is ...?''  Be careful to note the word difference (i.e., ``variable'' versus ``variability'' when answering these questions.}

\vspace{-12pt}
\warn{The precision to which a quantitative variable was recorded does not determine whether it is continuous or discrete. How precisely the variable COULD have been recorded is the important consideration.}

\begin{exsection}
  \item \label{revex:VarTypeDucks} What type of variable is the number of ducks found at the ``Hot Pond'' every morning? \ansref{ans:VarTypeDucks}
  \item \label{revex:VarTypeGenetics} What type of variable is the genotype (AA, Aa, aa) of a particular species of sunflower? \ansref{ans:VarTypeGenetics}
  \item \label{revex:VarTypeGenetics2} What type of variable is the length of petals on individual flowers? \ansref{ans:VarTypeGenetics2}
  \item \label{revex:VarTypeGenetics3} What type of variable is the number of seeds produced by an individual sunflower? \ansref{ans:VarTypeGenetics3}
  \item \label{revex:VarTypeGenetics4} What type of variable is the ``quality'' of the seeds produced by an individual plant (``quality'' is recorded as 1=poor, 2=low, 3=good, and 4=excellent)? \ansref{ans:VarTypeGenetics4}
  \item \label{revex:VarTypeSOS} What type of variable is student rankings (``Excellent'', ``Very Good'', ``Good'', ``Fair'', ``Poor'') of a professor's abilities? \ansref{ans:VarTypeSOS}
  \item \label{revex:VarTypeAudit} What type of variable is whether an account is valid or invalid? \ansref{ans:VarTypeAudit}
  \item \label{revex:VarTypeDefects} What type of variable is the number of defects produced by a machine? \ansref{ans:VarTypeDefects}
  \item \label{revex:VarTypeBottles} What type of variable is the ounces of cola in a sample of 100 bottles? \ansref{ans:VarTypeBottles}
  \item \label{revex:VarTypeFish} What type of variable is the sex of fish collected from a lake? \ansref{ans:VarTypeFish}
  \item \label{revex:VarTypeFrogs} What type of variable is the number of legs on frogs collected in Bayfield County? \ansref{ans:VarTypeFrogs}
  \item \label{revex:VarTypeCroak} What type of variable is the frequency (mhz) of a bullfrog's ``croak''? \ansref{ans:VarTypeCroak}
  \item \label{revex:VarTypeTowns} What type of variable is the number of incorporated towns in a county? \ansref{ans:VarTypeTowns}
  \item \label{revex:VarTypeWeasels} What type of variable is the qualitative size of least weasels (small, medium, large)? \ansref{ans:VarTypeWeasels}
\end{exsection}
