---
layout: page
title: R Handout
subtitle: Getting Data Into R
author: Derek H. Ogle
css: /css/modules.css
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: no
  pdf_document: 
    fig_width: 3.5
    fig_height: 3.5
  word_document:
    fig_width: 3.5
    fig_height: 3.5
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules")
source("../rhelpers/rhelpers.R")
modHTML("DataIntoR_RHO")
```
```{r echo=FALSE, results='hide', message=FALSE, warnings=FALSE}
source("../rhelpers/knitr_setup.R")
purl2("DataIntoR_RHO.Rmd",moreItems=c("Renders","source","modHTML","github.com","NCMTH107"))
```

## Always First Command
```{r echo=-2, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
```

----

## Basic Data Frames
```{r echo=FALSE}
dfobj <- read.csv("https://github.com/droglenc/NCData/raw/master/Iris.csv")
```
```{r eval=FALSE}
setwd("C:/stats/")
dfobj <- read.csv("Iris.csv")
```
```{r}
str(dfobj)
headtail(dfobj)     # NOT the entire data.frame
```

## Working With Data Frames
```{r}
dfobj$seplen
dfobj$species
```

## Filtering Data Frames
```{r}
set <- filterD(dfobj,species=="setosa")
str(set)

gt5 <- filterD(dfobj,seplen>5)
headtail(gt5)

setver1 <- filterD(dfobj,species!="virginica")
str(setver1)

setver <- filterD(dfobj,species %in% c("setosa","versicolor"))
str(setver)

ver_and_gt5 <- filterD(dfobj,species=="versicolor",seplen>5)
headtail(ver_and_gt5)

ver_or_gt5 <- filterD(dfobj,species=="versicolor" | seplen>5)
headtail(ver_or_gt5)
```
