---
title: "Answer Key"
subtitle: "Getting Data Into R CE"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules")
source("../rhelpers/rhelpers.R")
modHTML("GettingDataIntoR_CE_Keys")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../rhelpers/knitr_setup.R")
```

----

The following two commands were run before the code run below because I saved all of my files in the same directory.
```{r eval=FALSE}
library(NCStats)
setwd("T:/Stats")
```


## Loading Data from Webpage
#### **BrainHead.csv**
```{r echo=FALSE}
bhobj <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/BrainHead.csv")
```

1. There are `r kCounts(ncol(bhobj))` variables in BrainHead.csv.
1. The variables in Brainhead.csv are: `r paste(names(bhobj),collapse=", ")`.
1. There are `r kCounts(nrow(bhobj))` individuals in BrainHead.csv.

```{r eval=FALSE}
bhobj <- read.csv("BrainHead.csv")
str(bhobj)
```

#### **PopularKids.csv**
```{r echo=FALSE}
pkobj <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/PopularKids.csv")
```

1. There are `r kCounts(ncol(pkobj))` variables in PopularKids.csv.
1. The variables in PopularKids.csv are: `r paste(names(pkobj),collapse=", ")`.
1. There are `r kCounts(nrow(pkobj))` individuals in PopularKids.csv.

```{r eval=FALSE}
pkobj <- read.csv("PopularKids.csv")
str(pkobj)
```

#### **Yahara.csv**
```{r echo=FALSE}
yobj <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/Yahara.csv")
```

1. There are `r kCounts(ncol(yobj))` variables in Yahara.csv.
1. The variables in Yahara.csv are: `r paste(names(yobj),collapse=", ")`.
1. There are `r kCounts(nrow(yobj))` individuals in Yahara.csv.

```{r eval=FALSE}
yobj <- read.csv("Yahara.csv")
str(yobj)
```

----

## Loading Your Own Data

* Answers will vary by student.

----

## Coarse Woody Debris

```{r}
cwd <- read.csv("cwd.csv")
( cwd.low <- filterD(cwd,exposure=="low") )
( cwd.gt20 <- filterD(cwd,diameter>20) )
( cwd.lowget20 <- filterD(cwd,exposure=="low",diameter>20) )
( cwd.btw2030 <- filterD(cwd,diameter>20,diameter<30) )
```

----

## Cars

```{r echo=FALSE}
car <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/93cars.csv")
```
```{r eval=FALSE}
car <- read.csv("93cars.csv")
```

```{r}
str(car)
( fords <- filterD(car,MFG=="Ford") )
( goodgas <- filterD(car,CMPG>30) )
( nostick <- filterD(car,Manual=="No",HMPG>30) )
( hpsub <- filterD(car,HP>175,HP<200) )
anor <- filterD(car,Domestic=="Yes"|Cyls==4) # large, didn't show result
```

----
