---
layout: page
title: Class Exercise
subtitle: Univariate EDA - Quantitative II (Interpretation)
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/")
source("../rhelpers/rhelpers.R")
modHTML("UEDAQuant2_CE3")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../rhelpers/knitr_setup.R")
```

----

## Mean Versus Median

Using the `meanMedian()` function with no arguments will open a plot constructed from random data that looks like that below.

```{r echo=FALSE, fig.height=4, fig.width=5}
meanMedian()
```

The top plot is a histogram. The lower plot shows individuals above the median (blue vertical line) with red dots and individuals below the median with black dots. In addition, the dashed horizontal lines represent the differences of each individual from the mean (red vertical line) with negative values in black and positive values in red.

In RStudio, this plot will also have a small "gear" icon in the upper-left corner. Clicking the gear opens a dialog box where you can control the sample size, two shape parameters, and whether an outlier is modeled or not. In the questions below, leave the sample size at 30 and press the "rerandomize" button several times.

1. Identify (i) the shape of the distribution, (ii) whether a substantive outlier is present, and (iii) whether the value of the mean is more or less than the value of the median when `shape1=5`, `shape2=1`, and there are no outliers.
1. Identify (i) the shape of the distribution, (ii) whether a substantive outlier is present, and (iii) whether the value of the mean is more or less than the value of the median when `shape1=1`, `shape2=5`, and there are no outliers.
1. What conclusion can you make about the effect of the shape of the distribution on the relative values of the mean and median?
1. What would expect the relative values of the mean and median to be if the distribution was perfectly symmetric?
1. Identify (i) the shape of the distribution, (ii) whether a substantive outlier is present, and (iii) whether the value of the mean is more or less than the value of the median when `shape1=3`, `shape2=3`, and there is an outlier at the minimum value.
1. Identify (i) the shape of the distribution, (ii) whether a substantive outlier is present, and (iii) whether the value of the mean is more or less than the value of the median when `shape1=3`, `shape2=3`, and there is an outlier at the maximum value.
1. Can you make a conclusion about the effect of outliers on the relative values of the mean and median?
1. Return to the [Shape and Outliers I](UEDAQuant2_CE1.html#shape-and-outliers-i) class exercse and, for each histogram, identify whether the mean would be less than, greater than, or approximately equal to the median.
1. Why do you think the mean and median behave this way?

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="UEDAQuant2.html">^</a></li>
  <li><a href="UEDAQuant2_CE1.html">1</a></li>
  <li><a href="UEDAQuant2_CE2.html">2</a></li>
  <li class="active"><a href="#">3</a></li>
  <li><a href="UEDAQuant2_CE4.html">4</a></li>
  <li><a href="UEDAQuant2_CE5.html">5</a></li>
</ul>
