---
layout: page
title: Class Exercise
subtitle: Univariate EDA - Quantitative I (Methods)
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules")
source("../rhelpers/rhelpers.R")
modHTML("UEDAQuant1_CE1")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../rhelpers/knitr_setup.R")
```

----

## Histograms I

The [U.S. Census](http://www.indexmundi.com/facts/united-states/quick-facts/all-states/average-commute-time#map) asked individuals 16 years old and older "How long in minutes is your one-way commute to work each day?".  The mean for individuals from each state was computed and is plotted in the histogram below.

```{r echo=FALSE, fig.width=4, fig.height=4, par1=TRUE}
df <- data.frame(time=c(24.2,18.8,24.6,21.3,27.2,24.5,24.8,24.8,29.7,25.9,27,
                        26,20,28,23.2,18.8,19,22.8,24.9,23.3,32,28,24,22.9,
                        23.9,23.1,18,18.1,23.8,26.3,30.4,21.6,31.6,23.6,16.9,
                        23,21,22.5,25.9,23.6,23.5,16.9,24.3,25,21.4,22.2,27.7,
                        25.7,25.5,21.7,18.3))
hist(~time,data=df,breaks=seq(16,32,2),xaxt="n",xlab="Mean Commute Time (mins)")
axis(1,seq(16,32,2))
```

Use this histogram to answer these questions.

1. What is an individual in this example?
1. What is the variable in this example?
1. What type of variable is recorded?
1. How many individuals are represented in this histogram?
1. How many individuals had a mean commute time between 16 and 18 minutes?
1. How many states had a mean commute time between 18 and 24 minutes?
1. What was the range of mean commute times for the bin with exactly five states?

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="UEDAQuant1.html">^</a></li>
  <li class="active"><a href="#">1</a></li>
  <li><a href="UEDAQuant1_CE2.html">2</a></li>
</ul>
