---
layout: page
title: Class Exercise
subtitle: Univ EDA - Quantitative Methods 2
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules")
source("../rhelpers/rhelpers.R")
modHTML("UEDAQuant1_CE2")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../rhelpers/knitr_setup.R")
```

----

## Hand Calculations

Consider the following three data sets for the questions below.  Show your work for all questions.

<pre>
Data Set 1
18 28 25 21 16 24

Data Set 2
4 54 16 85 52 29 24 71 61 60 2

Data Set 3
93 81 34 5 54 84 54 13 1 35 79 63 97 71
</pre>

1. Hand calculate the mean of Data Set 1.
1. Hand calculate the standard deviation of Data Set 1.
1. Hand calculate the median of Data Set 2.
1. Hand calculate the IQR of Data Set 2.
1. Hand calculate the median of Dat Set 3.
1. Hand calculate the IQR of Dat Set 3.
1. Hand calculate the range of Data Set 3.

You can check your work with `sdCalc()` and `iqrCalc()`.  For example,
```{r}
d <- c(16,23,47,13,18,12)
sdCalc(d)
iqrCalc(d)
```

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="UEDAQuant1.html">^</a></li>
  <li><a href="UEDAQuant1_CE1.html">1</a></li>
  <li class="active"><a href="#">2</a></li>
</ul>
