---
layout: page
title: "Foundations in R"
author: "Derek H. Ogle"
output:
  html_document:
    fig_width: 3.5
    self_contained: no
  word_document:
    fig_width: 3.5
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/lecture/HOs"); source("../../rhelpers/rhelpers.R")
fnm <- "FoundationsR"
modHTML(fnm)
```

```{r echo=FALSE, results='hide', message='FALSE'}
fnm <- "FoundationsR"
source("../../rhelpers/knitr_setup.R")
```

## Always First Command
```{r echo=-2, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
```


```{r eval=FALSE, echo=FALSE}
## Basic Mathematics
3-pi
junk <- 3-pi
junk
b <- 3.8
h <- 4.2
(1/2)*b*h
( result <- log(17) )
ls()
```

## Basic Vectors
```{r}
( profs <- c("Derek","Young","Jodi") )
( nums <- c(4,2,6,4,3) )
( heads <- c(TRUE, TRUE, FALSE, FALSE) )
ls()
nums[3]
profs[2]
heads[1]
```

## Basic Data Frames
```{r}
setwd("C:/aaaWork/Web/GitHub/NCMTH107/lecture/HOs")
iris <- read.csv("Iris.csv")
str(iris)
headtail(iris)     # NOT the entire data.frame
ls()
```

## Working With Data Frames
```{r}
iris[2,]
iris$seplen
iris$seplen[3]
iris[3,2]
iris[c(1,3,5),]
```

## Filtering Data Frames
```{r}
set <- filterD(iris,species=="setosa")
str(set)

gt5 <- filterD(iris,seplen>5)
headtail(gt5)

setver1 <- filterD(iris,species!="virginica")
str(setver1)

setver <- filterD(iris,species %in% c("setosa","versicolor"))
str(setver)

ver_and_gt5 <- filterD(iris,species=="versicolor",seplen>5)
headtail(ver_and_gt5)

ver_or_gt5 <- filterD(iris,species=="versicolor" | seplen>5)
headtail(ver_or_gt5)

ls()
```

```{r echo=FALSE, results="hide", message=FALSE, warnings=FALSE}
purl2(paste0(fnm,".Rmd"))
```

