---
layout: page
title: Chi-Square Distribution
subtitle: R Handout
author: Derek H. Ogle
css: /css/modules.css
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: no
  pdf_document:
    fig_width: 3.5
    fig_height: 3.5
  word_document:
    fig_width: 3.5
    fig_height: 3.5
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/Chi_Square")
source("../../rhelpers/rhelpers.R")
fnm <- "RHO1"
modHTML(fnm)
```

```{r echo=FALSE, results='hide', message=FALSE}
fnm <- "RHO1"
source("../../rhelpers/knitr_setup.R")
```

----

## First Commands
```{r message=FALSE, warning=FALSE}
library(NCStats)
```

## Chi-Square Distribution Calculations
An example of computing the p-value $\chi^{2}$=2.67 and df=3.
```{r par1a=TRUE}
( distrib(2.67,distrib="chisq",df=3,lower.tail=FALSE) )
```

An example of computing the p-value if $\chi^{2}$=16.82 and df=8.
```{r par1a=TRUE}
( distrib(16.82,distrib="chisq",df=8,lower.tail=FALSE) )
```

```{r echo=FALSE, results="hide", message=FALSE, warnings=FALSE}
purl2(paste0(fnm,".Rmd"))
```
