---
layout: page
title: "Inference Concepts"
subtitle: R Handout
author: "Derek H. Ogle"
css: "/css/modules.css"
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: false
    lib_dir: libs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/HO/")
source("../../rhelpers/rhelpers.R")
modHTML("1SampleZ_RHO")
purl2("1SampleZ_RHO.Rmd",moreItems=c("Renders","source","modHTML","github.com","NCMTH107"))
```

----

## Background
The [Survey of Study Habits and Attitudes (SSHA)](http://www.jstor.org/stable/1434291?seq=1#page_scan_tab_contents) was a psychological test that measures the motivation, attitudes, and study habits of college students. Scores range from 0 to 200 and follow (approximately) a normal distribution, with a mean of 110 and a standard deviation of 20.  The survey was given to 40 "non-traditional" students to test the hypothesiis that they had stronger study habits and greater motivation for school work.

The results of the study are in [SSHA.csv](https://github.com/droglenc/NCData/raw/master/SSHA.csv).  Use these data to test the hypothesis at the 5% level.

----

## Getting the Data
```{r echo=FALSE}
d <- read.csv("https://github.com/droglenc/NCData/raw/master/SSHA.csv")
```
```{r message=FALSE, warning=FALSE}
library(NCStats)
```
```{r eval=FALSE}
setwd("C:/stats/")
d <- read.csv("SSHA.csv")
```
```{r}
str(d)
```

## Quick EDA
```{r par1=TRUE}
Summarize(~score,data=d,digits=1)
hist(~score,data=d,xlab="SSHA Score")
```

## 1-Sample Z-test
```{r par1a=TRUE}
( z1 <- z.test(d$score,sd=20,mu=110,alt="greater",conf.level=0.95) )
plot(z1)
```
