---
layout: page
title: Simple Linear Regresssion
subtitle: R Handout
author: Derek H. Ogle
css: /css/modules.css
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: false
    lib_dir: libs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/HO/")
source("../../rhelpers/rhelpers.R")
modHTML("LinearRegression_RHO")
purl2("LinearRegression_RHO.Rmd",moreItems=c("Renders","source","modHTML","github.com","NCMTH107"))
```

----

## Background
[Lindstrom et al. (2000)](http://www.ncbi.nlm.nih.gov/pubmed/10667974) examined the change in [pectoral muscle](http://www.birdwatchingdaily.com/blog/2014/01/30/the-amazing-muscles-and-bones-that-make-birds-fly/) size of [Red Knots (*Calidris canutus*)](https://en.wikipedia.org/wiki/Red_knot) during periods of sustained flight and fasting.  Their primary objective was to determine if these birds extracted energy from the pectoral muscle during times of high activity and stress and then if the muscle was rebuilt relatively quickly.  In one part of their study, they examined whether variability in the mass (g) of the pectoral muscle could be explained by knowing the thickness (mm) of the pectoral muscle.

These two variables are recorded in [AvianPecMusc.csv](https://github.com/droglenc/NCData/raw/master/AvianPecMusc.csv).  Use this information to answer the questions below.

* What is the response variable?
* What is the explanatory variable?
* In terms of the variables of this problem, what is the equation of the best-fit line?
* In terms of the variables of this problem, interpret the value of the slope.
* In terms of the variables of this problem, interpret the value of the y-intercept.
* What is the predicted pectoral muscle mass if the pectoral muscle thickness is 10 mm?
* What is the predicted pectoral muscle mass if the pectoral muscle thickness is 30 mm?
* What is the residual if the pectoral muscle mass is 12 g and the pectoral muscle thickness is 10 mm?
* What is the correlation coefficient between the pectoral muscle mass and thickness?
* What proportion of the variability in pectoral muscle mass is explained by knowing the pectoral muscle thickness?
* What aspect of this regression analysis concerns you (i.e., consider the regression assumptions)?

----

## Getting the Data
```{r echo=FALSE}
d <- read.csv("https://github.com/droglenc/NCData/raw/master/AvianPecMusc.csv")
```
```{r message=FALSE, warning=FALSE}
library(NCStats)
```
```{r eval=FALSE}
setwd("C:/stats/")
d <- read.csv("AvianPecMusc.csv")
```
```{r}
str(d)
headtail(d)
```

## Fitting the Regression and Seeing the Results
```{r par1=TRUE}
( lm.mt <- lm(mass~thickness,data=d) )
rSquared(lm.mt)
fitPlot(lm.mt,ylab="Pectoral Muscle Mass (g)",xlab="Pectoral Muscle Thickness (mm)")
```

## Using the Regression
```{r}
( predM <- predict(lm.mt,data.frame(thickness=10)) )
12-predM
```
