---
layout: page
title: Review Exercise
subtitle: Normal Distributions
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/RE/")
source("../../rhelpers/rhelpers.R")
modHTML("NormalDist_RevEx_Simple")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../rhelpers/knitr_setup.R")
```

----

## Normal Distribution Characteristics I

Identify the mean and standard deviation for each population on the graph below (HINT: "eyeball" integers).

```{r NormDistGuess1, echo=FALSE}
par(mar=c(3.5,0.5,0.5,0.5),mgp=c(1.7,0.4,0),las=1,tcl=-0.2,yaxs="i")
x <- seq(-5,7,by=0.001)
B <- dnorm(x,-1,1)
A <- dnorm(x,1,2)
plot(B~x,type="l",lwd=3,xlab="Quantitative Variable (X)",
     ylab="",yaxt="n",xlim=c(-5,7),ylim=c(0,1.01*max(c(A,B))),col="red")
lines(B~x,lwd=3,col="red")
lines(A~x,lwd=3,col="blue")
abline(v=seq(-5,7,1),lwd=1,lty=3,col="lightgray")
text(-2.5,0.2,"B",col="red",cex=2)
text(3.5,0.13,"A",col="blue",cex=2)
```

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#NormDist1">See Answer Here</a>
</div>
</div>
<div id="NormDist1" class="panel-collapse collapse">
<div class="panel-body">A~N(1,2) and B~N(-1,1)</div>
</div>
</div>
</div>

----

## Normal Distribution Characteristics II

Identify the mean and standard deviation for each population on the graph below (HINT: "eyeball" integers).

```{r NormDistGuess2, echo=FALSE}
par(mar=c(3.5,0.5,0.5,0.5),mgp=c(1.7,0.4,0),las=1,tcl=-0.2,yaxs="i")
x <- seq(-20,60,by=0.001)
B <- dnorm(x,20,10)
A <- dnorm(x,30,5)
plot(B~x,type="l",lwd=3,xlab="Quantitative Variable (X)",
     ylab="",yaxt="n",xlim=c(-15,55),ylim=c(0,1.01*max(c(A,B))),col="red")
lines(B~x,lwd=3,col="red")
lines(A~x,lwd=3,col="blue")
grid(ny=NA)
text(3,0.02,"B",col="red",cex=2)
text(38,0.06,"A",col="blue",cex=2)
```

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#NormDist1">See Answer Here</a>
</div>
</div>
<div id="NormDist1" class="panel-collapse collapse">
<div class="panel-body">A~N(30,5) and B~N(20,10)</div>
</div>
</div>
</div>

----

## 68-95-99.7 (Empirical) Rule

You can click on each question to see an answer. Click on it again to close the answer.

<div class="panel-group">

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule1">On any normal distribution, what percentage of individuals is within &plusmn;1&sigma; of &mu;?</a>
</div>
</div>
<div id="EmpRule1" class="panel-collapse collapse">
<div class="panel-body">68%</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule2">On any normal distribution, what percentage of individuals is within &plusmn;3&sigma; of &mu;?</a>
</div>
</div>
<div id="EmpRule2" class="panel-collapse collapse">
<div class="panel-body">99.7%</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule3">On any normal distribution, what percentage of individuals is greater than &mu;+&sigma;?</a>
</div>
</div>
<div id="EmpRule3" class="panel-collapse collapse">
<div class="panel-body">16%</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule4">On any normal distribution, what percentage of individuals is less than &mu;-2&sigma;?</a>
</div>
</div>
<div id="EmpRule4" class="panel-collapse collapse">
<div class="panel-body">2.5%</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule5">On any normal distribution, what percentage of individuals is between &mu;-2&sigma; and &mu;+&sigma;?</a>
</div>
</div>
<div id="EmpRule5" class="panel-collapse collapse">
<div class="panel-body">81.5% (using the results from the previous two questions ... 100-16-2.5).</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule6">On a N(1,1), what percentage of individuals are negative?</a>
</div>
</div>
<div id="EmpRule6" class="panel-collapse collapse">
<div class="panel-body">16% (Note that negative means less than 0, 0 is one &sigma; below &mu; on this distribution, and 16% of individuals are less than one &sigma; below &mu;.</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule7">On a N(100,20), what percentage of individuals are less than 80?</a>
</div>
</div>
<div id="EmpRule7" class="panel-collapse collapse">
<div class="panel-body">16% (16% of individuals are less than one &sigma; below &mu;.</div>
</div>
</div>
  
<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule8">On a N(-20,100), what percentage of individuals are greater than 80?</a>
</div>
</div>
<div id="EmpRule8" class="panel-collapse collapse">
<div class="panel-body">16% (16% of individuals are greater than one &sigma; above &mu;.</div>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title">
<a data-toggle="collapse" href="#EmpRule9">On a N(50,20), what percentage of individuals are less than 60?</a>
</div>
</div>
<div id="EmpRule9" class="panel-collapse collapse">
<div class="panel-body">This question cannot be answered with the 68-95-99.7 Rule because 60 is not an integer number of &sigma;s away from &mu;.</div>
</div>
</div>

</div>

----
