---
title: "Answer Key"
subtitle: "Univariate EDA - Categorical CE"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/UnivEDA_Categorical/")
source("../../rhelpers/rhelpers.R")
modHTML("CE_Keys")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../rhelpers/knitr_setup.R")
```

----

## Hand Calculations

*Should be performed by hand to match results below*

<ol>
<li>Frequency Table</li>
```{r echo=FALSE}
d <- read.csv("breeds.csv")
( tbl <- xtabs(~breed,data=d) )
```

<li>Percentage Table</li>
```{r}
percTable(tbl,digits=1)
```

<li>Bar Chart</li>
```{r echo=FALSE, fig.width=6, fig.height=3, par1=TRUE}
barplot(tbl,xlab="Breed of Dog",ylab="Frequency of Wins")
```

<li><i>Can not Bring Myself to Make One</i></li>
</ol>

----

## Bar Chart I

<ol>
<li>A Northland College student.</li>
<li>Categorical, nominal.</li>
<li>Frequency table is below.</li>
```{r echo=FALSE}
( d <- c(Love=45,Money=1,Pregnancy=0,Other=4) )
```
<li>Percentage table is below.</li>
```{r echo=FALSE}
round(d/sum(d)*100,1)
```
</ol>
 
----

## Coarse Woody Debris

1. The vast majority (82%) of the sites had medium exposure.
```{r echo=FALSE}
d <- read.csv("../UnivEDA_Quantitative/cwd.csv")
```
```{r eval=FALSE}
d <- read.csv("cwd.csv")
```
```{r}
xtabs(~exposure,data=d)
```
 
----

## Bar Chart II

1. A Brown Pelican in the Northern Gulf of Mexico.
1. The habitat used is categorical, nominal.
1. 62%
1. 26%
1. 12% (100-62-26)
1. Cannot address shape of bar charts.

----

## Popularity in Middle School

<ol>
<li>The goal for most kids was getting good grades, followed by being popular, and then being good in sports.</li>
```{r echo=FALSE}
d <- read.csv("https://github.com/droglenc/NCData/raw/master/PopularKids.csv")
```
```{r eval=FALSE}
d <- read.csv("PopularKids.csv")
```
```{r, fig.width=4, fig.height=3, par1=TRUE}
( tbl <- xtabs(~goals,data=d) )
barplot(tbl,xlab="Student's Goal",ylab="Frequency",ylim=c(0,250))
```
<li>Students feel that "being good in sports" is an important contributor to popularity as approximately 2/3rds of studens ranked this as either "most important" or "somewhat important" to being popular.</li>
```{r, fig.width=4, fig.height=3, par1=TRUE}
tbl <- xtabs(~sports,data=d)
percTable(tbl,digits=1)
barplot(tbl,xlab="Rank of Sports in Popularity",ylab="Frequency",ylim=c(0,200))
```

<li>Students were nearly evenly distributed among rural, suburban, and urban schools.  Students were likely sampled nearly equally from each type of school.</li>
```{r, fig.width=4, fig.height=3, par1=TRUE}
( tbl <- xtabs(~type,data=d) )
barplot(tbl,xlab="School Type",ylab="Frequency",ylim=c(0,200))
```
</ol>

----
