---
title: "First Day Preparations"
author: "Dr. Derek H. Ogle"
date: "January 3, 2017"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You are currently enrolled in **MTH107 -- Statistical Concepts and Analyses**.  Below are several announcements regarding this course.

* A website with all of the course materials is at http://derekogle.com/NCMTH107/. 
* There is no commercial textbook for this course.  Rather, I will provide PDFs on the course website for each module of material. Note that the materials to be provided are considerably changed from previous semesters so I would NOT buy a "textbook" used in previous semesters.
* You may want to install some software on your personal computer (which you may use during class if you so choose). Directions for installing R, RStudio, and necessary packages are at the bottom of [the Resources page on the course website](http://derekogle.com/NCMTH107/resources/).  Let me know if you need assistance installing these softwares.
* You should prepare for the first day of class by
    * Reading the syllabus (see the ["syllabus" tab](http://derekogle.com/NCMTH107/resources/Syllabus-Current) at the top of the course website). We will not discuss the syllabus in detail, but you are responsible for all the material therein.
    * Following the preparation directions for the "Why Statistics is Important" module (use the ["modules" tab on the website, then select the first module](http://derekogle.com/NCMTH107/modules/Why_Statistics_is_Important/)). This material will be covered on the first day of class.

Please let me know if you have any questions.
