---
layout: page
title: Homework Assignment
subtitle: Bivariate EDA - Quantitative
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/BivEDA_Quantitative/")
source("../../rhelpers/rhelpers.R")
modHTML("HW")
```

```{r echo=FALSE, results='hide', message=FALSE}
source("../../rhelpers/knitr_setup.R")
```

----

<div class="alert alert-warning">
<strong>Note:</strong> Your answers to the questions below should follow the <a href="../../resources/hwformat" target="_blank">expectations for homework found here</a> (and <a href="../../resources/FAQ/FAQs/HWFormat_Example.pdf" target="_blank">demonstrated here</a>). Date due on <a href="../../resources/Dates-Current.html" target="_blank">Dates page</a>.
</div>

----

## Animal Fat and Breast Cancer

[Carroll (1975)](https://www.ncbi.nlm.nih.gov/pubmed/1104150) examined the relationship between per capita consumption of animal fat (g/day; AnimFatI) and age-adjusted death rate from breast cancer (AgeAdjDe) for 39 countries.  Use the following results from her data to describe the bivariate relationship between these two variables.

```{r echo=FALSE, fig.width=3.5, fig.height=3.5, par1=TRUE}
cf <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/CancerFat.csv")
plot(adjdeath~fatintake,data=cf,pch=16,xlab="Fat Intake (g/day)",
     ylab="Age-Adjusted Death Rate")
r <- round(cor(cf$adjdeath,cf$fatintake),3)
legend("topleft",legend=paste0("r=",r),bty="n")
```

----

## North Fish Creek Discharge

The instantaneous discharge (cubic feet per second) and total suspended sediments (in milligrams per liter) were recorded on 28 dates for North Fish Creek near Ashland, WI.  These data are found in FishCrNWaterQuality.csv ([data](https://raw.githubusercontent.com/droglenc/NCData/master/FishCrNWaterQuality.csv), [meta](https://raw.githubusercontent.com/droglenc/NCData/master/FishCrNWaterQuality_meta.txt)). Describe the relationship between instantaneous discharge and total suspended sediments from these data.

----
