---
title: "Answer Key"
subtitle: "Summaries for One Quantitative Variable CE"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/CE/1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_UEDAQuant1_CE")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
library(captioner)
tbls <- captioner(prefix="Table")
figs <- captioner(prefix="Figure")
tbls(name="Brain1","Summary statistics for brain weight (g).")
tbls(name="Brain2","Summary statistics for brain weight (g) separated by age group.")
figs(name="Brain1","Histogram of brain weight (g).")
figs(name="Brain2","Histograms of brain weight (g) separated by age group.")
```

----

## Hand Calculations

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
<li>Make sure to show your work when calculating the standard deviation. The method shown below is one way to show your work that produces consistent results. On assessments, not showing your work will result in a zero for the question.</li>
<li>Don't forget to arrange the values from smallest to largest when computing the median. Count the original and your arranged data to make sure you have the same number of values in both.</li>
<li>The median will be one of the observed values if n is odd, but it will be the average of two observed values if n is even.<li>
<li>If n is odd such that the median is one of the observed values, then that value is not included in either "half" of the data when computing the IQR. In other words, the "lower half" of the data will end right before the median and the "upper half" of the data will end right after the median. See Data Set 2 below.<li>
</ul>
</div>

<ol>
<li>Shown below</li>
```{r}
sdCalc(c(18,28,25,21,16,24))
```
<li>Shown above</li>
<li>Shown below</li>
```{r}
iqrCalc(c(4,54,16,85,52,29,24,71,61,60,2))
```
<li>Shown above</li>
<li>Shown below</li>
```{r}
iqrCalc(c(93,81,34,5,54,84,54,13,1,35,79,63,97,71))
```

<li>Shown above</li>
<li>Range is 1 to 97.</li>
</ol>

----

## Histograms I

1. An individual is a state.
1. The variable is the mean commute time for indivuals 16-years and older in states of the U.S.
1. Mean Commute time (mins) is a quantitative, continuous variable.
1. 51
1. 2
1. 25
1. 26-28

----

## Brain Weights
```{r echo=FALSE}
d <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/BrainHead.csv")
```

<ol>
<li>The histogram of brain weights is in `r figs("Brain1",display="cite")`.</li>
```{r BrainHist1, echo=FALSE, fig.width=3, fig.height=3, par1=TRUE}
hist(~brain.weight,data=d,xlab="Brain Weight (g)")
```

`r figs("Brain1")`

<li>The summary statistics for brain weights is in `r tbls("Brain1",display="cite")`.</li>

`r tbls("Brain1")`

```{r BrainSum1, echo=FALSE, background="white"}
Summarize(~brain.weight,data=d,digits=1)
```

<li>The histogram of brain weights separated by age group is in `r figs("Brain2",display="cite")`.</li>
```{r BrainHist2, echo=FALSE, fig.width=6, fig.height=3, par1=TRUE}
hist(brain.weight~age.group,data=d,xlab="Brain Weight (g)")
```

`r figs("Brain2")`

<li>The summary statistics of brain weights separate by age groups is in `r tbls("Brain2",display="cite")`.</li>

`r tbls("Brain2")`

```{r BrainSum2, echo=FALSE, background="white"}
Summarize(brain.weight~age.group,data=d,digits=1)
```
</ol>

R Appendix.
```{r eval=FALSE, prompt=FALSE}
d <- read.csv("data/BrainHead.csv")
<<BrainHist1>>
<<BrainSum1>>
<<BrainHist2>>
<<BrainSum2>>
```

----
