---
title: "Annotated Key"
subtitle: "Normal Distributions Class Example"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_NormalDist1_CExmpl")
```
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
```

```{r echo=FALSE, results="hide"}
library(NCStats)
library(ggplot2)

library(ggplot2)
library(NCStats)

mn <- 70
sd <- 6
brks <- mn+seq(-3,3,by=1)*sd

b <- ggplot(data.frame(x=c(-Inf,Inf)),mapping=aes(x=x)) +
  stat_function(fun=dnorm,args=list(mean=mn,sd=sd),xlim=c(mn-4*sd,mn+4*sd),
                geom="line",color="black",size=1.1) +
  scale_y_continuous(expand=expansion(mult=c(0,0.04))) +
  scale_x_continuous(breaks=brks,expand=expansion(mult=c(0,0))) +
  theme_NCStats() +
  theme(axis.title.y=element_blank(),axis.title.x=element_text(size=16),
        axis.text.x=element_text(size=12),axis.text.y=element_blank())
```

## Wood Duck Weights
1. The percentage of wood ducks that weight between 350 and 550 g is 95%.

<div class="alert alert-warning">
<p>This follows directly from the middle part of the 68-95-99.7% Rule because 350 is exactly 2&sigma; below &mu; and 550 is exactly 2&sigma; above &mu;.</p>

```{r echo=FALSE}
b + labs(x="Height (in)") +
  stat_function(fun=dnorm,args=list(mean=mn,sd=sd),xlim=c(mn-2*sd,mn+2*sd),
                geom="area",fill="gray20",color="black",size=1.1) +
  ggpmisc::geom_text_npc(aes(npcx=0.5,npcy=0.05,label="95%"),
                         size=11,color="white")
```

</div>

&nbsp;

{:start="2"}
1. The percentage of wood ducks that weight more than 550 g is 2.5%.

