---
title: "Answer Key"
subtitle: "Filtering Data In R CE"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/CE/1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_FilteringDataInR_CE")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
```

----

The following two commands were run before the code run below because I saved all of my files in the same directory.
```{r eval=FALSE}
library(NCStats)
setwd("T:/Stats")
```

----

## Coarse Woody Debris
```{r}
cwd <- read.csv("cwd.csv")
( cwd.low <- filterD(cwd,exposure=="low") )
( cwd.gt20 <- filterD(cwd,diameter>20) )
( cwd.lowget20 <- filterD(cwd,exposure=="low",diameter>20) )
( cwd.btw2030 <- filterD(cwd,diameter>20,diameter<30) )
```

----

## Cars
```{r echo=FALSE}
car <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/93cars.csv")
```
```{r eval=FALSE}
car <- read.csv("93cars.csv")
```
```{r}
str(car)
( fords <- filterD(car,MFG=="Ford") )
( goodgas <- filterD(car,CMPG>30) )
( nostick <- filterD(car,Manual=="No",HMPG>30) )
( hpsub <- filterD(car,HP>175,HP<200) )
anor <- filterD(car,Domestic=="Yes"|Cyls==4) # large, didn't show result
```

----

## Purple Loosestrife Plants
```{r echo=FALSE, results='hide'}
df <- data.frame(
lstrf=c(13,2,1,0,9,11,5,5,14,23,0,2,3,3,6,7,4,16,1),
shade=c("O","S","S","S","O","O","S","P","O","O","S","S","P","P","P","P","S","O","S"))
```
```{r eval=-(1:2)}
setwd('C:/aaaWork/Books/IntroStats/HW/')
df <- read.csv("loostrife.csv")
( shady <- filterD(df,shade=="S") )
( open <- filterD(df,shade=="O") )
( notshady <- filterD(df,shade!="S") )
( gt10 <- filterD(df,lstrf>10) )
( shadygt10 <- filterD(df,shade=="S",lstrf <5) )
```
