---
title: "Answer Key"
subtitle: "Confidence Regions CE 1"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/CE/1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_ConfRegions_CE1")
```

## The Concept of Confidence Intervals

1. The percentage of CIs that contained &mu; was not affected by (i.e., did not change) increasing n.
1. The percentage of CIs that contained &mu; increased with an increasing level of confidence.
1. The margin-of-error decreased with increasing n (i.e., the confidence interval became narrower).
1. The margin-of-error increased with increasing level of confidence (i.e., the confidence interval became wider).
1. As a statistican you can make the CI narrower by increasing your sample size (n) or decreasing the level of confidence (C). Decreasing the level of confidence, however, will result in more errors in your conclusions (i.e., &mu; will be contained within the confidence interval less often).

## Confidence Region Calculations

These questions were included on the second confidence regions assignment.
