---
title: "Answer Key"
subtitle: "2-Sample t CEx"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/CE/1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_2Samplet_CEx")
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
library(captioner)
tbls <- captioner(prefix="Table")
figs <- captioner(prefix="Figure")
tbls(name="Deliveries","Results from the two-sample t-test for testing that the mean delivery time was lower for the Bosnian than the Persian Gulf war.")
figs(name="DeliveriesHist","Histograms of the delivery times for military supplies in the Bosnian and Persian Gulf war.")
tbls(name="mussels1","Levene's test results for testing equal variances among impacted and reference groups.")
tbls(name="mussels2","Two-sample t-test results for testing that the mean mercury levels in mussels differed between the impacted and reference sites.")
```

----

## Compost Type and Germination Rates
```{r GerminationCalc, echo=FALSE, results='hide', fig.show='hide'}
xbar1 <- 0.278; s1 <- 0.134; n1 <- 13
xbar2 <- 0.356; s2 <- 0.128; n2 <- 12
df <- n1+n2-2
( sp2 <- ((n1-1)*(s1^2)+(n2-1)*(s2^2))/df )
( se <- sqrt(sp2*(1/n1+1/n2)) )
( stat <- xbar1-xbar2 )
( t <- stat/se )
( pv <- distrib(round(t,3),distrib="t",df=df) )
( tstar <- distrib(0.025,type="q",distrib="t",df=df) )
( ci <- stat+c(1,-1)*tstar*se )
```

<ol>
<li>&alpha; = 0.05.</li>
<li>H<sub>A</sub>: &mu;<sub>bf</sub> - &mu;<sub>lp</sub> &ne; 0 and H<sub>0</sub>: &mu;<sub>bf</sub> - &mu;<sub>lp</sub> = 0, where &mu; is the mean reduction in LDL, bf is befizal, and lp is lipanthyl.</li>
</ol>

<div class="alert alert-warning">
<ul>
  <li>The hypotheses can also be written as -- H<sub>A</sub>: &mu;<sub>bf</sub> &ne; &mu;<sub>lp</sub> and H<sub>0</sub>: &mu;<sub>bf</sub> = &mu;<sub>lp</sub> -- because if two values are thought to be equal then the difference between those values would be equal to 0 and if they are thought to differ than the difference between the two would be diffrent from zero.</li>
  <li>I like the subscripts to be meaningful; hence, I used bf and lp here rather than 1 and 2, for example.</li>
  <li>It is best to order the parameters alphabetically; thus, I had the bf group before the lp group. This is not a huge deal mathematically but it will be important when using R to perform a two-sample t-test.</li>
  <li>Remember to define the parameter and, here, also the subscripts on the parameters.</li>
</ul>
</div>

<ol start="3">
  <li>A 2-sample t-test will be used because</li>
  <ol type="i">
    <li>two groups/populations are considered (befizal and lipanthyl drugs),</li>
    <li>a quantitative variable (reduction in LDL) was recorded, and</li>
    <li>individuals in the groups are independent (there is no known connection between individuals in the befizal and individuals in the lipanthyl groups; e.g., it is not the same or related individuals in the two groups).</li>
  </ol>
</ol>

<div class="alert alert-warning">
<ul>
  <li>These are the three characteristics that separate a 2-sample t-test from other tests we will see this semester.</li>
  <li>Please include some sort of description that shows that the characteristics are met and that you are not just listing the characteristics -- in other words, include the parts in parentheses.</li>
  <li>The independence characteristic is the most difficult to write in my opinion. Basically what you have to describe is that there is no direct connection between individuals in one group and indviduals in the other group. A lack of independence in this example could be that the same people were in both drug groups (think of a before-after study) or that siblings were split into the two groups (so one sibling was always "connected" genetically to their sibling in the other group).</li>
  <li>If the two groups have different sample sizes (as is the case here) then you automatically know that there is independence because for individuals to be connected there would have to be the same number per group.</li>
</ul>
</div>

<ol start="4">
  <li>This study is largely experimental because the experimenter decided which individuals received which drug treatment. The subjects were randomly allocated to treatments but were not randomly selected from a larger population.</li>
</ol>

<div class="alert alert-warning">
<ul>
  <li>You will start seeing more "experiments" in the 2-sample tests.</li>
  <li>With experiments (as compared to observational studies) you need to address two levels of randomization. First, were the individuals randomly selected from a larger popuation. If they were then you CAN make inferences to the larger population; however, if they were not then you cannot. Second, were the individuals randomly allocated to treatments. If they were then you can make cause-and-effect conclusions; however, if not they you cannot. So, in this example the research may draw cause-and-effect conclusions (because of random allocation) but those conclusions may not generalize to the larger population of men (because there was no random selection).</li>
</ul>
</div>

<ol start="5">
  <li>The assumptions are met because (i) the samples are independent (as described above), (ii) n<sub>bf</sub>+n<sub>lp</sub> = 13+12 = 25 &ge; 15 and the two sample distributions (histograms shown on the handout) are not obviously strongly skewed, and (iii) the variances appear to be equal (Levene's p-value = 0.8315 &gt; &alpha;).</li>
</ol>  
  
<div class="alert alert-warning">
<ul>
  <li>If the combined sample size is less than 30 then you need to assess the skewness of the histograms. As with the 1-sample t-test, this assumption no longer refers to the population distributions.</li>
  <li>The "equal variances" assumption is assessed with a Levene's Test. The hypotheses for the Levene's test are H<sub>0</sub>: &sigma;<sup>2</sup><sub>bf</sub> = &sigma;<sup>2</sup><sub>lp</sub> (i.e., variances are equal) and H<sub>A</sub>: &sigma;<sup>2</sup><sub>bf</sub> &ne; &sigma;<sup>2</sup><sub>lp</sub> (i.e., variances are unequal). Thus, if the p-value from the Levene's test is greater than &alpha; the variances are considered equal, the assumption is met, and you can continue with the 2-sample t-test.</li>
  <li>In "hand-calculation" questions like this one, you will always be given the Levene's test p-value (as was done here). You will compute the p-value using R when you have the raw data available (this will be discussed later).</li>
</ul>
</div>

<ol start="6">
  <li>x&#772;<sub>bf</sub>-x&#772;<sub>lp</sub> = `r xbar1`-`r xbar2` = `r stat`.</li>
  <li>The values for each mean are from the summary table given in <a href="../CEx/2Samplet_CExmpl">the background</a>.
</ol>

<div class="alert alert-warning">
  <ul>
    <li>The "statistic" in a 2-sample t-test will always be the difference in the sample means, calculated in the same way that the difference in population means is shown in the hypotheses (i.e., alphabetically if you used that).</li>
    <li>This statistic will be negative about half the time. That just means that the mean of the first group is less than the mean of the second group.</li>
  </ul>
</div>

<div class="alert alert-info">
  <p>The next step requires two intermediate calculations with the following values given in <a href="../CEx/2Samplet_CExmpl">the background</a>.
  <ul>
  <li>n<sub>bf</sub> = `r n1`; n<sub>lp</sub> = `r n2`</li>
  <li>s<sub>bf</sub> = `r s1`; s<sub>lp</sub> = `r s1`.</li>
  </ul>  
  <p>The intermediate calculations are computed below.</p>
  <ul>
  <li>The pooled sample variance is `r formatC(sp2,format="f",digits=4)` as computed below.</li>

\[s_{p}^{2}=\frac{(n_{1}-1)s_{1}^{2}+(n_{2}-1)s_{2}^{2}}{n_{1}+n_{1}-2} \]

\[s_{p}^{2}=\frac{(13-1)0.134^{2}+(12-1)0.128^{2}}{13+12-2} \]
    
  <li>The standard error of the statistic is `r formatC(se,format="f",digits=3)` as computed below.</li>

\[ SE_{\bar{x}_{1}-\bar{x}_{2}}=\sqrt{s_{p}^{2}\left(\frac{1}{n_{1}}+\frac{1}{n_{2}} \right)}  \]

\[ SE_{\bar{x}_{bf}-\bar{x}_{lp}}=\sqrt{0.0172\left(\frac{1}{13}+\frac{1}{12} \right)}  \]
  </ul>
</div>

<ol start="7">
  <li>With the intermediate calculations from above t = $\frac{(\bar{x}_{bf}-\bar{x}_{lp})-0}{SE_{\bar{x}_{bf}-\bar{x}_{lp}}}$ = $\frac{-0.078-0}{0.053}$=`r formatC(t,format="f",digits=3)` with n<sub>bf</sub>+n<sub>lp</sub>-2 = 13+12-2 = `r df` df.</li>
  <li>p-value`r kPvalue(pv,include.p=FALSE,latex=FALSE)` (more specifically `r formatC(pv,digits=4)`) as computed with `2*distrib(-1.485,distrib="t",df=23)`.</li>
<li>Reject H<sub>0</sub> because the p-value &lt; &alpha;.</li>
<li>It appears that the the mean reduction in LDL does NOT differ between subjects given Befizal and those given Lipanthyl. Thus, neither drug should be preferred with respect to reducing the LDL in patients.</li>
</ol>

<div class="alert alert-warning">
  <ul>
    <li>For the sake of learning for other examples, if we had rejected the null hypothesis (because the p-values<&alpha;) then the initial conclusion would be that the mean LDL did differ between the two drugs. However, we would be able to say more than that because the Lipanthyl drug had a greater mean reduction than the Befizal in the sample. Thus, we would conclude that Lipanthyl works better because it reduced the mean LDL more. Again, this was not the case with this sample, I just put this here to think about might happen in a different example.</li>
  </ul>
</div>

<div class="alert alert-warning">
<p>I performed the following steps or calculations in preparation for the next step.</p>
  <ul>
    <li>95% confidence (because &alpha;=0.05)</li>
    <li>Confidence interval because H<sub>A</sub> was "not equals."
    <li>t<sup>*</sup>=&pm;`r formatC(tstar,format="f",digits=3)` as computed with `distrib(0.025,distrib="t",df=23,type="q").
    <li>`r formatC(stat,format="f",digits=3)`&pm;`r formatC(tstar,format="f",digits=3)`*`r formatC(se,format="f",digits=3)` (where `r formatC(stat,format="f",digits=3)` is from Step 6 and `r formatC(se,format="f",digits=3)` is the SE computed for Step 7).
  </ul>
</div>

<ol start="11">
<li>I am 95% confident that the DIFFERENCE in the mean reduction in LDL from those given befizal to those given lipanthyl is between `r formatC(ci[1],format="f",digits=3)` and `r formatC(ci[2],format="f",digits=3)`. Thus, the mean reduction in LDL for befizal patients could be between `r formatC(-1*ci[2],format="f",digits=3)` greater and `r formatC(ci[1],format="f",digits=3)` lower than the mean reduction in LDL for lipanthyl patients.
</ol>

<div class="alert alert-warning">
<ul>
  <li>This step requires the most care in the 2-sample t-test because the confidence region is for the DIFFERENCE in means. This confidence region is NOT about either mean. So please take note of the wording above.</li>
  <li>Note that if confidence region contains zero then that means you will not have rejected H<sub>0</sub> as this suggests that it is possible that the DIFFERENCE in means is zero, whih suggests no difference. This will lead to awkward statements like that above where you say that one group be more or it could be less than the other group.</li>
  <li>Make sure you are careful about how the DIFFERENCE was calculated. In this case it was befizal-lipanthyl (alphabetically). Thus, negative values mean that befizal was smaller/lower (or, equivalently, lipanthyl was larger/greater) and positive values mean that befizal was larger/greater (or equivalently, lipanthyl was smaller/lower).</li>
</ul>
</div>

----
