---
layout: page
title: Dates Current
author: "Derek H. Ogle"
css: "/css/syllabus.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/resources/")
source("../rhelpers/rhelpers.R")
modHTML("Dates-Current")
```

<div class="alert alert-info">
For each class period ("Date"), the module to prepare for is shown under "Topic." Some of the more distant dates are subject to change.
</div>

<div class="alert alert-warning">
**Group Blackwell** will meet from 815-945 on weeks 1, 3, 5, and 7 and from 10-1130 on weeks 2, 4, and 6. **Group Nightingale** will meet from 815-945 on weeks 2, 4, and 6 and from 10-1130 on weeks 1, 3, 5, and 7. <a href="Groups_Current.html">Group assignments are here.</a>
</div>

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
options(knitr.kable.NA = '')
## Read data, make data with day and topic with link
d <- readxl::read_excel("Dates_F20A.xlsx") %>%
  dplyr::mutate(Date=as.Date(Date)) %>%
  dplyr::filter(Date>=lubridate::today()) %>%
  dplyr::mutate(Date=paste0(DOW,", ",format(Date,"%b-%d")),
                Topic=ifelse(is.na(url),Topic,
                       paste0('<a href=\"../modules/',url,'\">',Topic,'</a>'))) %>%
  dplyr::select(Date,Topic)
## Put a blank row after each Friday
blank_rows <- grep("F",d$Date)
if (blank_rows[length(blank_rows)]==nrow(d)) blank_rows <- blank_rows[-length(blank_rows)]
for (i in rev(blank_rows))
  d <- dplyr::add_row(d,Date=NA,Topic=NA_character_,.after=i)
## Make the kable
knitr::kable(d,format="html",escape=FALSE) %>%
  kableExtra::kable_styling(bootstrap_options=c("condensed","hover","responsive"),
                            full_width=FALSE,position="center",
                            fixed_thead=TRUE)
```

<br>

<br>

# Past Dates


```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
options(knitr.kable.NA = '')
## Read data, make data with day and topic with link
d <- readxl::read_excel("Dates_F20A.xlsx") %>%
  dplyr::mutate(Date=as.Date(Date)) %>%
  dplyr::filter(Date<lubridate::today()) %>%
  dplyr::mutate(Date=paste0(DOW,", ",format(Date,"%b-%d")),
                Topic=ifelse(is.na(url),Topic,
                       paste0('<a href=\"../modules/',url,'\">',Topic,'</a>'))) %>%
  dplyr::select(Date,Topic)
## Put a blank row after each Friday
blank_rows <- grep("F",d$Date)
if (blank_rows[length(blank_rows)]==nrow(d)) blank_rows <- blank_rows[-length(blank_rows)]
for (i in rev(blank_rows))
  d <- dplyr::add_row(d,Date=NA,Topic=NA_character_,.after=i)
## Make the kable
knitr::kable(d,format="html",escape=FALSE) %>%
  kableExtra::kable_styling(bootstrap_options=c("condensed","hover","responsive"),
                            full_width=FALSE,position="center",
                            fixed_thead=TRUE)
```

