---
layout: page
title: Symbols
author: "Derek H. Ogle"
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/resources/")
source("../rhelpers/rhelpers.R")
modHTML("symbols")
```

## Critical
The following symbols (ordered approximately as they were introduced) are **CRITICAL** to doing well in this course. **You will be expected to know these on an instant recall basis.**

<div class="panel panel-info">
<div class="panel-heading">Symbol <span class="pull-right">Definition</span></div>
<div class="panel-body">
<dl class="dl-horizontal">
<dt>n</dt><dd>Sample size.</dd>
<dt>$\bar{\textrm{x}}$</dt><dd>Sample mean (average) of the X variable.</dd>
<dt>s</dt><dd>Sample standard deviation.</dd>
<dt>&mu;</dt><dd>Population mean.</dd>
<dt>&sigma;</dt><dd>Population standard deviation.</dd>
<dt>X~N(&mu;,&sigma;)</dt><dd>The variable X is normally distributed with a mean of &mu; and standard deviation of &sigma;.</dd>
<dt>H<sub>0</sub></dt><dd>The null hypothesis.</dd>
<dt>H<sub>A</sub></dt><dd>The alternative hypothesis.</dd>
<dt>&alpha;</dt><dd>The rejection criterion OR probability of making a Type I error.</dd>
</dl>
</div>
</div>


## Important
The following symbols will be used often during the course and will be parts of multiple choice questions on quizzes. **You will need to know these symbols to do well in this course.**

<div class="panel panel-info">
<div class="panel-heading">Symbol <span class="pull-right">Definition</span></div>
<div class="panel-body">
<dl class="dl-horizontal">
<dt>Q1</dt><dd>First quartile.</dd>
<dt>Q3</dt><dd>Third quartile.</dd>
<dt>IQR</dt><dd>Interquartile range (Q3-Q1).</dd>
<dt>N(0,1)</dt><dd>Standard normal distribution.</dd>
<dt>&beta;</dt><dd>The probability of making a Type II error.</dd>
<dt>C</dt><dd>The level of confidence for a confidence region.</dd>
<dt>Z</dt><dd>A variable that follows a N(0,1) OR the test statistic in a one-sample Z-test.</dd>
<dt>t</dt><dd>A variable that follows a t-distribution OR the test statistic in t-tests.</dd>
<dt>s<sub>p</sub><sup>2</sup></dt><dd>Pooled sample variance in a 2-Sample t-Test.</dd>
<dt>&sigma;<sup>2</sup></dt><dd>Population variance.</dd>
<dt>df</dt><dd>Degrees-of-freedom.</dd>
<dt>&chi;<sup>2</sup></dt><dd>A variable that follows a chi-square distribution OR the test statistic in chi-square tests.</dd>
</dl>
</div>
</div>

## Useful
The following symbols will be used in the course, but less often than those above and will not be parts of multiple choice questions on quizzes.

<div class="panel panel-info">
<div class="panel-heading">Symbol <span class="pull-right">Definition</span></div>
<div class="panel-body">
<dl class="dl-horizontal">
<dt>N</dt><dd>Population size. [<emph>generally unknown</emph>]</dd>
<dt>x<sub>i</sub></dt><dd>Value of the X variable for the ith individual.</dd>
<dt>s<sup>2</sup></dt><dd>Sample variance.</dd>
<dt>M</dt><dd>The sample median. [<emph>rarely used</emph>]</dd>
<dt>c</dt><dd>The number of columns in a two-way frequency table.</dd>
<dt>r</dt><dd>The sample correlation coefficient OR number of rows in a two-way frequency table.</dd>
<dt>r<sup>2</sup></dt><dd>The coefficient of determination.</dd>
<dt>$\hat{\textrm{y}}_{\textrm{i}}$</dt><dd>Predicted value of the response variable (in regression).</dd>
<dt>RSS</dt><dd>Residual sum-of-squares.</dd>
<dt>&mu;<sub>0</sub></dt><dd>Specific value of &mu; in the H<sub>0</sub> of 1-Sample Z- and t-Tests.</dd>
<dt>p</dt><dd>Population proportion of successes.</dd>
<dt>$\hat{\textrm{p}}$</dt><dd>Sample proportion of successes.</dd>
</dl>
</div>
</div>


<style>
.panel .dl-horizontal dt {
    white-space: normal;
    width: 23%;
}
.panel .dl-horizontal dt:after {
    content: ":";
}
.panel .dl-horizontal dd {
    padding-left: 0.5em;
}

</style>

