---
title: "First Day Preparations"
author: "Dr. Derek H. Ogle"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You are currently enrolled in **MTH107 -- Statistical Concepts and Analyses**. Below are several announcements regarding this course.

* A website with all course materials is at http://derekogle.com/NCMTH107/. 
* There is no commercial textbook for this course. Rather, I will provide PDFs on the course website for each module of material. Note that the materials to be provided are considerably changed from previous semesters so I would NOT buy a "textbook" used in previous semesters.
* You may want to install some software on your personal computer. Directions for installing R, RStudio, and necessary packages are at the bottom of [the Resources page on the course website](http://derekogle.com/NCMTH107/resources#software-installation-links). Let me know if you need assistance installing these softwares.
* You should prepare for the first day of class by
    * Reading the syllabus (see the ["syllabus" tab](http://derekogle.com/NCMTH107/resources/Syllabus-Current) at the top of the course website). We will not discuss the syllabus in detail, but you are responsible for all the material therein.
    * Prepare **hand**-written answers to the questions in the preparation guide for the "Why Statistics is Important" module (use the "modules" tab on the website, then select the first module). This will require you to read the reading and watch the videos bulleted under the "Preparation for Class" section on that page. You will be responsible for preparing for this material for the first day of class (**and may be asked to hand in your hand-written answers to the questions in the preparation guide**).
* [See this FAQ](http://derekogle.com/NCMTH107/resources/FAQ/FAQs/videos) about watching the videos.

Please let me know if you have any questions.
