---
layout: page
title: Additional Exercises
subtitle: Bivariate EDA - Quantitative
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CE/")
source("../../rhelpers/rhelpers.R")
modHTML("BEDAQuant_CE2")
```

```{r echo=FALSE, results='hide', message=FALSE}
source("../../rhelpers/knitr_setup.R")
```

----

## Associations II

For each situation below, identify (a) the response variable (if possible) and (b) whether you would expect a positive, negative, or no (neutral) association between the pair of variables.  Explain your reasoning for both answers.

1. Proportion of population with a post-secondary education and proportion of the population that have been incarcerated.
1. Temperature and sales of ice cream.
1. Hours spent exercising and percent body fat.
1. Average annual amount of snowfall and proportion that support conceal-and-carry gun laws (recorded for states from across the U.S.)
1. Husbands' and wife's ages.
1. Golfers' putting success and distance of the putt.

----

## MORE EXERCISES HERE
