---
layout: page
title: Homework Assignment
subtitle: Bivariate EDA - Quantitative
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/")
source("../rhelpers/rhelpers.R")
modHTML("BEDAQuant_HW2")
```

```{r echo=FALSE, results='hide', message=FALSE}
source("../rhelpers/knitr_setup.R")
```

----

<div class="alert alert-warning">
<strong>Note:</strong> Your answers to the questions below should follow the <a href="../resources/hwformat" target="_blank">expectations for homework found here</a> (and <a href="../resources/FAQ/FAQs/HWFormat_Example.pdf" target="_blank">demonstrated here</a>). Date due on <a href="../resources/Dates-Current.html" target="_blank">Dates page</a>.
</div>

----

## Animal Fat and Breast Cancer

[Carroll (1975)](https://www.ncbi.nlm.nih.gov/pubmed/1104150) examined the relationship between per capita consumption of animal fat (g/day) and age-adjusted death rate from breast cancer for 39 countries. Use the following results from her data to describe the bivariate relationship between these two variables.

```{r echo=FALSE, fig.width=3.5, fig.height=3.5, par1=TRUE}
cf <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/CancerFat.csv")
plot(adjdeath~fatintake,data=cf,pch=16,xlab="Fat Intake (g/day)",
     ylab="Age-Adjusted Death Rate")
r <- round(cor(cf$adjdeath,cf$fatintake),3)
legend("topleft",legend=paste("r=",r,sep=" "),bty="n")
```

----

## Animal Longevity and Gestation

The average gestation period (i.e., length of pregnancy) of an animal is closely related to its longevity (i.e., length of its lifespan). Scientists are interested in being able to predict the average longevity (difficult to measure) from average gestation period (relatively easy to measure) for a given animal. Towards this end, data on the average gestation period and longevity (in captivity) of 40 different species of animals was recorded in animals.csv ([data](https://raw.githubusercontent.com/droglenc/NCData/master/animals.csv), [meta](https://raw.githubusercontent.com/droglenc/NCData/master/animals_meta.txt)). Describe the relationship between average longevity and average gestation period from these data. [*Think carefully about which variable should be on the y-axis.*]

----
