---
layout: page
title: "Answer Key"
subtitle: "1-Sample Z CE"
author: Derek H. Ogle
css: "/css/modules.css"
---


<pre><code>## Warning: package &#39;knitr&#39; was built under R version 3.6.1</code></pre>
<hr />
<div class="alert alert-warning">
<strong>Note:</strong> When performing the 11 steps, make sure to …
<ul>
<li>
Define the parameter μ in Step 2.
</li>
<li>
Provide some evidence for the characteristics of the test in Step 3 (note the items in parentheses).
</li>
<li>
Note that the decision is about H<sub>0</sub> in Step 9. However, in Step 10 you will likely be describing what you decided about H<sub>A</sub>. For example, in the first example below, Step 10 is saying that H<sub>A</sub> is not supported. However, the opposite is true in the second example. This happens because the researcher’s hypothesis (what they are tyring to see if there is evidence for) is almost always in H<sub>A</sub>. Therefore, answering the researcher’s question requires you to say whether H<sub>A</sub> was supported or not.
</li>
</ul>
</div>
<div id="diet-and-weight-gain" class="section level2">
<h2>Diet and Weight Gain</h2>
<ol>
<li>
α=0.05.
</li>
<li>
H<sub>A</sub>: μ&gt;5 and H<sub>0</sub>: μ=5, where μ is the mean weight gain for all women that followed the diet.
</li>
<li>
1-sample Z-test because (i) one group or population (women that followed this diet) was sampled, (ii) a quantitative variable (weight gain) was recorded, and (iii) σ is assumed to be known (=7.1).
</li>
<li>
An observational study as the women chose to be on the diet. There is clear randomization in this study.
</li>
<li>
The assumptions are met because (i) σ is known (=7.1) and (ii) n=35≥30.
</li>
<li>
x̄=6.7 pounds gained.
</li>
<li>
Z=1.4165.
</li>
<li>
p-value=0.0783.
</li>
<li>
Do not reject H<sub>0</sub> because the p-value&gt;α.
</li>
<li>
There is not enough evidence to conclude that the mean weight gain for ALL women on this diet is greater than 5 pounds.
</li>
<li>
Not required
</li>
</ol>
<p>R Appendix.</p>
<pre class="r"><code>xbar &lt;- 6.7; sigma &lt;- 7.1; n &lt;- 35
se &lt;- sigma/sqrt(n)
t &lt;- (xbar-5)/se
pv &lt;- distrib(t,lower.tail=FALSE)
lcb &lt;- xbar+distrib(0.95,lower.tail=FALSE,type=&quot;q&quot;)*se</code></pre>
<hr />
</div>
<div id="cactus-growth" class="section level2">
<h2>Cactus Growth</h2>
<ol>
<li>
α=0.05.
</li>
<li>
H<sub>0</sub>: μ = 4, H<sub>A</sub>: μ &lt; 4 where μ is the mean growth of all cacti.
</li>
<li>
A one-sample Z-test is required because (i) a quantitative variable (growth) was measured, (ii) individuals from only one group/population were sampled (only one set of conditions considered), and (iii) σ is known (given in the background).
</li>
<li>
The data are part of an experiment in which cacti were randomly selected.
</li>
<li>
σ is known. In addition, because the population distribution is normal (stated in the background), we do not have to worry about the size of the sample.
</li>
<li>
x¯ = 3.26.
</li>
<li>
Z = <span class="math inline">\(\frac{3.26-4}{\frac{1.40}{\sqrt{10}}}\)</span> = <span class="math inline">\(\frac{-0.74}{0.44}\)</span> = -1.67.
</li>
<li>
The p-value is 0.0473.
</li>
<li>
H<sub>0</sub> is rejected because the p-value&lt;α.
</li>
<li>
The mean growth rate of all cacti under the experimental conditions does appear to be less than 4 cm.
</li>
<li>
One is 95% confident that the mean growth of all cacti under the experimental conditions is less than 3.98 cm.
</li>
</ol>
<div id="r-appendix" class="section level3">
<h3>R Appendix</h3>
<pre class="r"><code>&gt; ( pval &lt;- distrib(3.26,mean=4,sd=1.40/sqrt(10)) )
&gt; ( zstar &lt;- distrib(0.95,type=&quot;q&quot;) )</code></pre>
<hr />
</div>
</div>
<div id="elk-density-in-banff" class="section level2">
<h2>Elk Density in Banff</h2>
<ol>
<li>
α=0.10
</li>
<li>
H<sub>O</sub>: μ=8, H<sub>A</sub>: μ&gt;8, where μ is the mean Elk density in Banff.
</li>
<li>
A 1-sample Z-test is required because a quantitative variable (Elk density) was measured on individuals from one group or population (plots in Banff National Park) and σ is known (given in background).
</li>
<li>
An observational sample that is not obiously random was selected.
</li>
<li>
The assumptions are met because n=15≥15 and the population is approximately normal (given in background) and σ is known.
</li>
<li>
The statistic is x̄=9.35 Elk per km<sup>2</sup> (Table 1).
</li>
<p>Table 1: Results from the one-sample z-test for testing that the mean density of elk in ALL plots in Banff is greater than 8 per km<span class="math inline">\(^{2}\)</span>.</p>
<pre><code>z = 2.6194, n = 15.000, Std. Dev. = 2.000, Std. Dev. of the sample mean = 0.516,
p-value = 0.004404
90 percent confidence interval:
 8.690876      Inf 
sample estimates:
mean of elk 
   9.352667 </code></pre>
<li>
The test statistic is Z=2.619 (Table 1).
</li>
<li>
The p-value is 0.0044 (Table 1).
</li>
<li>
The H<sub>O</sub> is rejected because the p-value&lt;α.
</li>
<li>
The annual density of elk appears to be greater than 8 per km<sup>2</sup>.
</li>
<li>
A 90% lower confidence bound is required. Thus, one is 90% confident that the mean annual density of elk is more than 8.69 per km<sup>2</sup> (Table 1).
</li>
</ol>
<p>R Appendix</p>
<pre class="r"><code>library(NCStats)
setwd(&#39;C:/aaaWork/Books/IntroStats/HW/&#39;)
elk &lt;- read.csv(&quot;Elk.csv&quot;)
( elk.z &lt;- z.test(elk,mu=8,sd=2,alt=&quot;greater&quot;,conf.level=0.90) )</code></pre>
<hr />
</div>
<div id="credit-card-limits" class="section level2">
<h2>Credit Card Limits</h2>
<ol>
<li>
α=0.10.
</li>
<li>
H<sub>A</sub>: μ&gt;630 and H<sub>O</sub>: μ=630, where μ is the mean credit card limit for all companies.
</li>
<li>
A one-sample Z-test is required because a quantitative variable (credit score) was measured on individuals from one group or population (all credit card companies) and σ is known (given in background).
</li>
<li>
An observational sample, with no evidence of randomness, was selected.
</li>
<li>
The assumptions are met because n=44≥30 and σ is known.
</li>
<li>
The statistic is x̄=636.86.
</li>
<li>
The test statistic is Z=<span class="math inline">\(\frac{636.86-630}{\frac{5}{\sqrt{44}}}\)</span>=9.11.
</li>
<li>
The p-value is &lt;0.00005.
</li>
<li>
The H<sub>O</sub> is rejected because the p-value&lt;α.
</li>
<li>
It appears that the credit threshold is greater than 630. Thus, it appears that the credit card companies have increased the threshold for issuing a credit card.
</li>
<li>
A 90% lower confidence bound with Z<sup>*</sup>=-1.282. Thus, 636.86-1.282<span class="math inline">\(\frac{5}{\sqrt{44}}\)</span> or 636.86-0.97 = 635.89. Therefore, one is 90% confident that the mean cutoff score for ALL companies is greater than 635.89.
</li>
</ol>
<p>R Appendix</p>
<pre class="r"><code>library(NCStats)
setwd(&#39;C:/aaaWork/Books/IntroStats/HW/&#39;)
( distrib(636.86,mean=630,sd=5/sqrt(44),lower.tail=FALSE) )
( distrib(0.90,type=&quot;q&quot;,lower.tail=FALSE,lower.tail=FALSE) )</code></pre>
<hr />
</div>
<div id="raptors-at-hawks-ridge" class="section level2">
<h2>Raptors at Hawk’s Ridge</h2>
<ol>
<li>
α=0.01
</li>
<li>
H<sub>O</sub>: μ=50000, H<sub>A</sub>: μ&gt;50000, where μ is the mean number of raptors seen in ALL years at Hawk’s Ridge.
</li>
<li>
A one-sample Z-test is required because (i) a quantitative variable (number of raptors) was measured, (ii)the individuals are from one group or population (all years at Hawk’s Ridge), and (iii) σ is known (=37000). Thus, the population mean is being compared to a specific value in the null hypothesis.
</li>
<li>
An observational sample of years that was not random was taken.
</li>
<li>
The assumptions are met because n=32≥30 and σ is known.
</li>
<li>
x̄=68183 (Table 2).
</li>
<p>Table 2: Results from the one-sample z-test for testing that the mean number of hawks observed at Hawk Ridge, MN is greater than 50000 per year.</p>
<pre><code>z = 2.78, n = 32.000, Std. Dev. = 37000.000, Std. Dev. of the sample mean =
6540.738, p-value = 0.002718
99 percent confidence interval:
 52967.06      Inf 
sample estimates:
mean of hr$Total 
        68183.09 </code></pre>
<li>
The test statistic is Z=2.780 (Table 2).
</li>
<li>
The p-value is 0.0027 (Table 2).
</li>
<li>
The H<sub>O</sub> is rejected because the p-value&lt;α (Table 2).
</li>
<li>
The mean number of raptors seen per year in ALL years appears to be greater than 50000.
</li>
<li>
I am 99% confident that the mean number of raptors seen per year in ALL years is more than 52967 (Table 2).
</li>
</ol>
<p>R Appendix</p>
<pre class="r"><code>hr &lt;- read.csv(&quot;https://github.com/droglenc/NCData/raw/master/HawksRidge.csv&quot;)
( hr.z &lt;- z.test(hr$Total,mu=50000,sd=37000,alt=&quot;greater&quot;,conf.level=0.99) )</code></pre>
<hr />
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
