---
layout: page
title: Assignment
subtitle: Sampling Distributions
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CE/")
source("../../rhelpers/rhelpers.R")
modHTML("SamplingDist_CE2")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../rhelpers/knitr_setup.R")
```

----

## Explore Central Limit Theorem
The Central Limit Theorem (CLT), the specifics of which are in your module preparation notes, provides a mechanism for understanding what the sampling distribution of the sample means looks like. In this exercise, you will first identify what the CLT says the shape, center, and dispersion of the sampling distribution of sample means should look like for different sample sizes (n) from the known population shown below.

```{r Sit1, echo=FALSE, fig.width=3.25, fig.height=3, par2=TRUE}
shape1 <- 6; shape2 <- 2
x <- seq(0,0.95,0.05)
y <- round(1000*stats::dbeta(x,shape1,shape2),0)
x <- rep(x, y)
title.popn <- substitute(paste(mu,"=",muval,", ",sigma,"=",sigmaval),
                         list(muval=formatC(shape1/(shape1+shape2),
                                            format="f",digits=2),
                              sigmaval=formatC(sqrt((shape1*      shape2)/(((shape1+shape2)^2)*(shape1+shape2+1))),
                                               format="f",digits=3)))
old.par <- par(mar=c(3,2,2.25,1),mgp=c(1.7,0.4,0),tcl=-0.2,yaxs="i")
hist(x,freq=FALSE,breaks=seq(0,1,0.05),yaxt="n",xlab="Variable (X)",
     ylab="",main="",right=FALSE,col="gray90")
mtext("Population Distribution",3,line=1.3)
mtext(title.popn,3,line=0.1)
mtext("Frequency of Individuals",2,line=0.1)
par(old.par)
```

<ol>
  <li>What is the shape (normal or not), center (a specific value), and dispersion (a specific value) of the population shown in the plot above? [Note: Put specific symbols on the values for center and dispersion.]</li>
<br>
  <li>Based on the CLT record (in the table below) what you would expect the sampling distribution of the sample means to look like for samples of n=10, 25, and 50 taken from this population.</li>
</ol>

<table class="table table-bordered table-condensed" style="width:65%">
<thead>
<tr><th></th><th colspan=3 class="text-center">Expected from CLT</th></tr>
<tr><th>&nbsp;</th><th class="text-center">Normal?</th><th class="text-center">Center</th><th class="text-center">Dispersion</th></tr>
</thead>
<tbody>
<tr><td>n=10</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>n=25</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>n=50</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
</tbody>
</table>

<br>
<br>

The sampling distribution of the sample means can be simulated by computing the means from many repeated samples from a population. The `cltSim()` function (with no arguments) efficiently computes sample means from many samples taken from a known population. The plots below were created with `cltSim()`. The histogram on the left below is the known population distribution (with &mu; &amp; &sigma; as shown). The histogram on the right is the distribution of sample means from 5000 samples of size n from the known population (i.e., a simulated sampling distribution).

```{r echo=FALSE, fig.width=7,fig.height=3,par2=TRUE}
cltSim()
```

In RStudio, a gear icon will be in the upper-left corner of this plot that will open a dialog box that allows you to change two shape parameters to alter the known population distribution. The population shown above uses `shape1=6` and `shape2=2`. You should set those two sliders to those values and make sure that the population distribution (left plot) matches the population further above.

<ol start="3">
  <li>Record what you observed about the sampling distribution of sample means (right plot) for each of n=10, 25, and 50 in the appropriate cells of the table below. [Use the "n" slider under the gear icon.]</li>
</ol>

<table class="table table-bordered table-condensed" style="width:65%">
<thead>
<tr><th></th><th colspan=3 class="text-center">Observed from <code>cltSim()</code></th></tr>
<tr><th>&nbsp;</th><th class="text-center">Normal?</th><th class="text-center">Center</th><th class="text-center">Dispersion</th></tr>
</thead>
<tbody>
<tr><td>n=10</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>n=25</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>n=50</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
</tbody>
</table>

<br>
<br>

Evidence to support (or not) the CLT can be obtained by comparing what you expected to see (based on the CLT) for the sampling distribution of sample means to what you actually observed in the simulated distributions.

<ol start="4">
  <li>Did each of your observations (second table) match your expectations (first table)?</li>
  <li>Do your observations on this exercise give you confidence in the CLT? Why or why not?</li>
</ol>

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="../SamplingDist.html">^</a></li>
  <li><a href="SamplingDist_CE1.html">1</a></li>
  <li class="active"><a href="#">2</a></li>
  <li><a href="SamplingDist_CE3.html">3</a></li>
</ul>
