---
title: "25 - Chi-Square Test in R"
description: |
  Methods for computing results for chi-square and goodness-of-fit tests.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,fig.align='center',comment="#R>  ")
```




\vspace{12pt}
\section{Chi-Square test in R (Raw Data)}
\vspace{-3pt}
The data for a Chi-Square Test may be computed from raw data on individuals (this section) or entered from summarized data (see \sectref{sect:chiRSmrzd}). Raw data must be in stacked format where one column in the data.frame represents the response variable and another column represents the groups (see Sections \ref{sect:REnterData} and \ref{sect:2tData}). Raw data must be summarized into a two-way frequency table with \R{xtabs()} as described in \modref{chap:BivEDACat}. The two-way table must contain frequencies, not proportions or percentages (don't use \R{percTable()}), without marginal totals (don't use \R{addMargins()}).

The Chi-Square Test is performed with \R{chisq.test()}, which takes an observed frequency table either entered through \R{matrix()} or summarized with \R{xtabs()} as the first argument. The only other argument needed is \R{correct=FALSE} so that the continuity correction is not used.\footnote{The continuity correction is not used here simply so that the results using R will match hand-calculations. The continuity correction should usually be used.} The results of \R{chisq.test()} should be assigned to an object. The Chi-Square test statistic and p-value are extracted by simply printing the saved object. The expected frequency table is returned by appending \R{\$expected} to the saved object.

Rejecting the null hypothesis in a Chi-Square Test indicates that there is some difference in the distribution of individuals into the levels of the response variable among some of the groups. However, rejecting the null hypothesis does not indicate which groups are different. In addition, as mentioned previously, confidence intervals are generally not performed with a Chi-Square Test. A post-hoc method for helping determine which groups differ is obtained by observing the Pearson residuals.

A Pearson residual is computed for each cell in the table as,

\[ \frac{Observed-Expected}{\sqrt{Expected}} \]

which is the appropriately signed square root of the parts in the $\chi^2$ test statistic calculation. Therefore, cells that have Pearson residuals far from zero contributed substantially to the large $\chi^2$ test statistic that resulted in a small p-value and the ultimate rejection of $H_{0}$. Patterns in where the large Pearson residuals are found may allow one to qualitatively determine which groups differ and, thus, which levels of the response differ the most. This process will be illustrated more fully in the examples and review exercises. The Pearson residuals are obtained from the saved \R{chisq.test()} object by appending \R{\$residuals}.

\subsection{Example - Father Present at Birth}
Below are the 11-steps \sectrefp{sec:11Steps} for completing a full hypothesis test for the following situation:
\vspace{-8pt}
\begin{quote}
\textsl{Daniel Weiss (in ``100\% American'') reported the results of a survey of 300 first-time fathers from four different hospitals (labeled as A, B, C, and D). Each father was asked if he was present (or not) in the delivery room when his child was born. The results of the survey are in \href{https://raw.githubusercontent.com/droglenc/NCData/master/FatherPresent.csv}{FatherPresent.csv}. Use these data to determine if there is a difference, at the 5\% level, in the proportion of fathers present in the delivery room among the four hospitals.}
\end{quote}

<<echo=FALSE>>=
fp <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/FatherPresent.csv")
@
<<ChiFP, echo=FALSE, results='hide', fig.show='hide'>>=
( fp.obs <- xtabs(~hospital+father,data=fp) )
( fp.chi <- chisq.test(fp.obs,correct=FALSE) )
fp.chi$expected
percTable(fp.obs,margin=1,digits=1)
@

\vspace{-6pt}
\begin{Enumerate}
  \item $\alpha$=0.05.
  \item $H_{0}$:``distribution of fathers presence (or not) during the birth of their child is the same for all four hospitals'' vs. $H_{A}:$ ``the distribution of fathers presence during the birth of their child is NOT the same for all four hospitals.''
  \item A Chi-Square Test is required because (i) a categorical variable (present or absent) was recorded and (ii) four groups are being compared (the hospitals).
  \item The data appear to be part of an observational study with no clear indication of randomization (likely a voluntary response survey).
  \item There are at least five individuals in each cell of the expected table \tabrefp{tab:ChiFPexp}.
  \item The statistic is the observed frequency table \tabrefp{tab:ChiFPobs}.
  \item $\chi^{2}$=\Sexpr{formatC(fp.chi$statistic,format="f",digits=3)} with \Sexpr{fp.chi$parameter} df \tabrefp{tab:ChiFPchi}.
  \item p-value=\Sexpr{kPvalue(fp.chi$p.value,include.p=FALSE)} \tabrefp{tab:ChiFPchi}.
  \item $H_{0}$ is not rejected because the p-value is $>\alpha$.
  \item The distribution of father's presence (or not) at their child's birth does not seem to differ significantly among hospitals where that birth occurred. For comparative purposes, the row-percentage table is in \tabref{tab:ChiFProw}.
\end{Enumerate}

\begin{minipage}{\textwidth}
\textbf{R Appendix:}
\vspace{-4pt}
<<eval=FALSE, results='hide', fig.show='hide', prompt=FALSE>>=
setwd("c:/data/")
fp <- read.csv("FatherPresent.csv")
<<ChiFP>>
@
\end{minipage}

\begin{table}[h]
  \caption{Expected frequency table for father's presence (or absence) during child birth among four hospitals.}
  \label{tab:ChiFPexp}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
fp.chi$expected
@
\end{table}

\begin{table}[h]
  \caption{Observed frequency table for father's presence (or absence) during child birth among four hospitals.}
  \label{tab:ChiFPobs}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
fp.obs
@
\end{table}

\begin{table}[h]
  \caption{Results from the Chi-Square Test for differences in father's presence during child birth among four hospitals.}
  \label{tab:ChiFPchi}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
kHtest(fp.chi)
@
\end{table}

\begin{table}[h]
  \caption{Percentage of father's presence (or absence) during child birth among four hospitals.}
  \label{tab:ChiFProw}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
percTable(fp.obs,margin=1,digits=1)
@
\end{table}


\vspace{6pt}
\section{Chi-Square test in R (Summarized Data)} \label{sect:chiRSmrzd}
\vspace{-3pt}
Two-way frequency datat that has already been summarized (outside of R) must be entered into a two-dimensional matrix. The frequencies must first be entered into a vector with the first row of values followed by the second row and so on. This vector is then the first argument to \R{matrix()}, which will also include the number of rows in the frequency table in \R{nrow=} and \R{byrow=TRUE} (which causes the values in the vector to be entered into the matrix in a row-wise manner). The process of entering summarized data into a matrix is better explained by example.

Suppose that you are given this observed frequency table.

\begin{center}
  \begin{tabular}{c|c|c|c|c|c|c|c|}
    \multicolumn{1}{c}{} & \multicolumn{6}{c}{Species} & \multicolumn{1}{c}{} \\
    \cline{2-7}
    Location & A & B & C & D & E & F & \multicolumn{1}{c}{} \\
    \hline
    \multicolumn{1}{|c|}{DI} & 34 & 22 & 14 & 13 & 12 & 5 & \textbf{100} \\
    \hline
    \multicolumn{1}{|c|}{BP} & 62 & 12 & 8 & 7 & 6 & 5 & \textbf{100} \\
    \hline
    & \textbf{96} & \textbf{34} & \textbf{22} & \textbf{20} & \textbf{18} & \textbf{10} & \textbf{200} \\
    \cline{2-8}
  \end{tabular}
\end{center}

The observed frequencies, ignoring the marginal sums, are first entered into a vector called \R{freq} below, which is then transformed into a two-row matrix called \R{obstbl}.
<<>>=
( freq <- c(34,22,14,13,12,5,62,12,8,7,6,5) )
( obstbl <- matrix(freq,nrow=2,byrow=TRUE) )
@

The matrix is more informative if the rows and columns are named with \R{rownames()} and \R{colnames()} as shown below.
<<>>=
rownames(obstbl) <- c("DI","BP")
colnames(obstbl) <- c("A","B","C","D","E","F")
obstbl
@

Once this observed table is constructed, the chi-square tests is performed exactly as described in the previous sections (i.e., starting with \R{chisq.test()}).

\subsection{Example - Apostle Islands Plants}
Below are the 11-steps \sectrefp{sec:11Steps} for completing a full hypothesis test for the following situation:
\vspace{-4pt}
\begin{quote}
\textsl{In her Senior Capstone project a Northland College student recorded the dominant (i.e., most abundant) plant species in 100 randomly selected plots on both Devil's Island and the Bayfield Peninsula (i.e., the mainland). There were a total of six ``species'' (one group was called ``other'') recorded (labeled as A, B, C, D, E, and F). The results are shown in the table below. Determine, at the 5\% level, if the frequency of dominant species differs between the two locations.}
\end{quote}

\begin{center}
  \begin{tabular}{c|c|c|c|c|c|c|c|}
    \multicolumn{1}{c}{} & \multicolumn{6}{c}{Species} & \multicolumn{1}{c}{} \\
    \cline{2-7}
    Location & A & B & C & D & E & F & \multicolumn{1}{c}{} \\
    \hline
    \multicolumn{1}{|c|}{DI} & 34 & 22 & 14 & 13 & 12 & 5 & \textbf{100} \\
    \hline
    \multicolumn{1}{|c|}{BP} & 62 & 12 & 8 & 7 & 6 & 5 & \textbf{100} \\
    \hline
    & \textbf{96} & \textbf{34} & \textbf{22} & \textbf{20} & \textbf{18} & \textbf{10} & \textbf{200} \\
    \cline{2-8}
  \end{tabular}
\end{center}

<<ChiAI, echo=FALSE, results='hide', fig.show='hide', warning=FALSE>>=
freq <- c(34,22,14,13,12,5,62,12,8,7,6,5)
ai.obs <- matrix(freq,nrow=2,byrow=TRUE)
rownames(ai.obs) <- c("DI","BP")
colnames(ai.obs) <- c("A","B","C","D","E","F")
( ai.chi <- chisq.test(ai.obs) )
ai.chi$expected
ai.chi$residuals
percTable(ai.obs,margin=1,digits=1)
ai.obs1 <- ai.obs[,-1]
( ai.chi1 <- chisq.test(ai.obs1) )
@

  \begin{Enumerate}
    \item $\alpha$=0.05.
    \item $H_{0}$: ``the distribution of dominant plants species is the same between Devil's Island and the Bayfield Peninsula'' vs. $H_{A}$: ``the distribution of dominant plants species is NOT the same between Devil's Island and the Bayfield Peninsula.''
    \item A Chi-Square Test is required because (i) a categorical variable with six levels (plant species) was recorded and (ii) two grouops are being compared (Devil's Island and Bayfield Peninsula).
    \item The data appear to be part of an observational study where the plots were randomly selected.
    \item There are more than five individuals in each cell of the expected table \tabrefp{tab:ChiAIexp}.
    \item The statistic is the observed frequency table given in the background.
    \item $\chi^{2}$=\Sexpr{formatC(ai.chi$statistic,format="f",digits=2)} with \Sexpr{ai.chi$parameter} df \tabrefp{tab:ChiAIchi}.
    \item p-value=\Sexpr{kPvalue(ai.chi$p.value,include.p=FALSE)} \tabrefp{tab:ChiAIchi}.
    \item $H_{0}$ is rejected because the p-value is $<\alpha$.
    \item There does appear to be a significant difference in the distribution of the dominant plants between the two sites. A look at the Pearson residuals \tabrefp{tab:ChiAIres} and the row-percentage table \tabrefp{tab:ChiAIrow} both suggest that the biggest difference between the two locations is due to ``plant A.''\footnote{When ``Plant A'' is removed from the observed table, the Chi-Square Test performed on the remaining plant species showed no difference in the distribution of the remaining plants between the two locations (\Sexpr{kPvalue(ai.chi1$p.value)}). Thus, most of the difference in plant distributions between Devil's Island and the Bayfield Peninsula appears to be due primarily to ``plant A'' with more of ``plant A'' found on the Bayfield Peninsula than on Devil's Island.}
  \end{Enumerate}

\begin{minipage}{\textwidth}
\textbf{R Appendix:}
<<eval=FALSE, results='hide', fig.show='hide', prompt=FALSE>>=
<<ChiAI>>
@
\end{minipage}

\begin{table}[h]
  \caption{Expected frequency table for dominant plant species on Devil's Island and the Bayfield Peninsula.}
  \label{tab:ChiAIexp}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
ai.chi$expected
@
\end{table}

\begin{table}[h]
  \caption{Results from the Chi-Square Test for differences in the distribution of dominant plant species between Devil's Island and the Bayfield Peninsula.}
  \label{tab:ChiAIchi}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
kHtest(ai.chi)
@
\end{table}

\begin{table}[h]
  \caption{Pearson residuals from the Chi-Square Test for differences in the distribution of dominant plant species between Devil's Island and Bayfield Peninsula.}
  \label{tab:ChiAIres}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
ai.chi$residuals
@
\end{table}

\begin{table}[h]
  \caption{Percentage of dominant plant species within each location (Devil's Island and Bayfield Peninsula).}
  \label{tab:ChiAIrow}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
percTable(ai.obs,margin=1,digits=1)
@
\end{table}










\vspace{18pt}
\section{Goodness-of-Fit Test in R}
\vspace{3pt}
\subsection{Data Format}
A Goodness-of-Fit Test is conducted in R with \R{chisq.test()}, which requires an observed table as the first argument. This observed table is entered from summarized data using \R{c()} or raw data is summarized to a frequency table with \R{xtabs()} as in \modref{chap:UnivEDACat}.

For example, suppose that the frequency of shrike observations in the ``mid-successional'', ``open'', ``scattered trees'', ``woods'', and ``wetland'' habitats is known to be 43, 1456, 112, 44 and 6, respectively. These summarized values are entered directly into a named vector below.
<<>>=
( obs <- c(MidSucc=43,Open=1456,ScatTree=112,Woods=6,Wetland=44) )
@

<<echo=FALSE>>=
shrike.raw <- data.frame(hab.use=factor(rep(names(obs),c(43,1456,112,44,6))))
@
However, instead of having summarized frequencies, suppose that the individual habitat observations were stored in a variable called \R{hab.use} in the \R{df} data.frame. These raw data must be summarized into a frequency table.
<<>>=
( obs <- xtabs(~hab.use,data=shrike.raw) )
@

\subsection{Goodness-of-Fit Test}
The Goodness-of-Fit Test is computed with \R{chisq.test()} with a observed frequencies as the first argument and the following arguments:
\vspace{-6pt}
\begin{Itemize}
  \item \R{p=}: a vector of expected proportions for the levels of the theoretical distribution.
  \item \R{rescale.p=TRUE}: rescales the values in \R{p=} to sum to 1. Rescaling is useful if the proportions in \R{p=} were rounded or are expected frequencies.
  \item \R{correct=FALSE}: indicates to not use a ``continuity correction.''\footnote{Some statisticians argue that small chi-square tables with small sample sizes should be corrected for the fact that the chi-square distribution is a continuous distribution. This correction is applied by simply subtracting 0.5 from each observed-expected calculation. We will not use the continuity correction in this course so that R calculations will match hand calculations.}
\end{Itemize}

The results from \R{chisq.test()} should be assigned to an object so that useful information can be extracted. The chi-square test statistics and p-value are extracted by typing the name of the saved object, the expected values are extracted by appending \R{\$expected} to the object, and a visual of the p-value is obtained by submitting the object to \R{plot()}. In addition, confidence intervals for the proportions of individuals in each level are constructed by submitting the saved object to \R{gofCI()}.

\subsection{Example - Loggerhead Shrikes}
Below are the 11-steps \sectrefp{sec:11Steps} for completing a full hypothesis test for the following situation:
\vspace{-4pt}
\begin{quote}
\textsl{\href{http://www.jstor.org/stable/4162345}{Bohall-Wood (1987)} constructed 24 random 16-km transects along roads in counties near Gainesville, FL. Two observers censused each transect once every 2 weeks from 18 October 1981 to 30 October 1982, by driving 32 km/h and scanning both sides of the road for perched and flying shrikes (\textbf{Lanius ludovicianus}). The habitat, whether the bird was on the roadside or actually in the habitat, and the perch type were recorded for each shrike observed. Habitats were grouped into five categories. The number of shrikes observed in each habitat was 1456 in open areas, 43 in midsuccessional, 112 in scattered trees, 44 in woods, and 6 in wetlands. Separate analyses were used to construct the proportion of habitat available in each of the five habitat types. These results were as follows: 0.358 open, 0.047 midsuccessional, 0.060 scattered trees, 0.531 woods, and 0.004 wetlands. Use these data to determine, at the 5\% level, if shrikes are using the habitat in proportion to its availability.}
\end{quote}

<<GOFshrikes, echo=FALSE, results='hide', fig.show='hide', warning=FALSE>>=
( obs <- c(Open=1456,MidSucc=43,ScatTree=112,Woods=6,Wetland=44) )
( p.exp <- c(Open=0.358,MidSucc=0.047,ScatTree=0.060,Woods=0.531,Wetland=0.004) )
( shrike.chi <- chisq.test(obs,p=p.exp,rescale.p=TRUE) )
data.frame(obs=shrike.chi$observed,exp=shrike.chi$expected)
gofCI(shrike.chi,digits=3)
@

\begin{Enumerate}
  \item $\alpha$=0.05.
  \item $H_{0}$:``distribution of habitat use by shrikes is the same as the proportions of available habitat'' vs. $H_{A}$:``distribution of habitat use by shrikes is NOT the same as the proportions of available habitat.''
  \item A Goodness-of-Fit Test is required because (i) a categorical variable was recorded (habitat use), (ii) a single group (or population) was considered (shrikes in this area), and (iii) the observed distribution is compared to a theoretical distribution.
  \item The data appear to be part of an observational study where the individuals were not randomly selected but the transects upon which they were observed were.
  \item There are more than five individuals expected in each habitat level \tabrefp{tab:GOFshrikesRes}.
  \item The statistic is the observed frequency table in \tabref{tab:GOFshrikesRes}.
  \item $\chi^2$=\Sexpr{formatC(shrike.chi$statistic,format="f",digits=1)} with \Sexpr{round(shrike.chi$parameter,0)} df \tabrefp{tab:GOFshrikesChi}.
  \item p-value\Sexpr{kPvalue(shrike.chi$p.value,include.p=FALSE)} \tabrefp{tab:GOFshrikesChi}.
  \item $H_{0}$ is rejected because the p-value$<\alpha$.
  \item The shrikes do not appear to use habitats in the same proportions as the availability of the habitat.
  \item The 95\% confidence intervals for the proportion of use in each habitat level are in \tabref{tab:GOFshrikesCIs}. From these results it appears that the shrikes use the ``open'' habitat much more often and the ``woods'' habitat mush less often than would be expected if they used all habitats in proportion to their availability.
\end{Enumerate}

\begin{minipage}{\textwidth}
\textbf{R Appendix:}
<<eval=FALSE, results='hide', fig.show='hide', prompt=FALSE>>=
<<GOFshrikes>>
@
\end{minipage}

\begin{table}[h]
  \caption{Observed and expected frequencies for the Goodness-of-Fit Test for shrike habitat use.}
  \label{tab:GOFshrikesRes}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
data.frame(obs=shrike.chi$observed,exp=shrike.chi$expected)
@
\end{table}

\begin{table}[h]
  \caption{Results from the Goodness-of-Fit Test for shrike habitat use.}
  \label{tab:GOFshrikesChi}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
kHtest(shrike.chi)
@
\end{table}

\begin{table}[h]
  \caption{Observed proportions, 95\% condidence intervals for the proprtions, and expected proportions for shrike habitat use.}
  \label{tab:GOFshrikesCIs}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
gofCI(shrike.chi,digits=3)
@
\end{table}

\vspace{18pt}
\subsection{Example - Modes of Fishing}
The 11-steps \sectrefp{sec:11Steps} for a hypothesis test for this example is below:
\vspace{-4pt}
\begin{quote}
\textsl{\href{http://www.mitpressjournals.org/doi/abs/10.1162/003465399767923827}{Herriges and King (1999)} examined modes of fishing for a large number of recreational saltwater users in southern California. One of the questions asked in their Southern California Sportfishing Survey was what ``mode'' they used for fishing -- ``from the beach'', ``from a fishing pier'', ``on a private boat'', or ``on a chartered boat.''  The results to this question, along with other data not used here, are found in \href{https://raw.githubusercontent.com/droglenc/NCData/master/FishingModes.csv}{FishingModes.csv}. One hypothesis of interest states that two-thirds of the users will fish from a boat, split evenly between private and charter boats, while the other one-third will fish from land, also split even between those fishing on the beach and those from a pier. Use the data in the \var{mode} variable of the data file to determine if this hypothesis is supported at the 10\% level.}
\end{quote}

<<echo=FALSE>>=
sf <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/FishingModes.csv")
@
<<GOFfish, echo=FALSE, results='hide', fig.show='hide', warning=FALSE>>=
obs <- xtabs(~mode,data=sf)
p.exp <- c(beach=1/6,boat=1/3,charter=1/3,pier=1/6)
( sf.chi <- chisq.test(obs,p=p.exp,rescale.p=TRUE) )
data.frame(obs=sf.chi$observed,exp=sf.chi$expected)
gofCI(sf.chi,digits=3)
@

\begin{Enumerate}
  \item $\alpha$=0.10.
  \item $H_{0}$:``The distribution will follow the proportions of $\frac{1}{3}$, $\frac{1}{3}$, $\frac{1}{6}$, and $\frac{1}{6}$ for private boat, charter boat, beach, and pier modes of fishing, respectively'' vs. $H_{A}$:``The distribution will NOT follow the proportions of $\frac{1}{3}$, $\frac{1}{3}$, $\frac{1}{6}$, and $\frac{1}{6}$ for private boat, charter boat, beach, and pier modes of fishing, respectively.''  [\textit{Thought process -- the two-thirds for ``boat'' fishing is split to one-third each for private and charter boats; the one-third, or two-sixths, for ``land'' fishing is split to one-sixth each for beach and pier fishing.}]
  \item A Goodness-of-Fit Test is required because (i) a categorical variable was recorded (mode), (ii) a single group (or population) was considered (Southern California Sportfishers), and (iii) the obseved distribution is compared to a theoretical distribution.
  \item The data appear to be part of an observational study where the individuals were not obviously (probably were not) randomly selected.
  \item There are more than five individuals expected in each mode \tabrefp{tab:GOFfishRes}.
  \item The statistic is the observed frequency table in \tabref{tab:GOFfishRes}.
  \item $\chi^2$=\Sexpr{formatC(sf.chi$statistic,format="f",digits=3)} with \Sexpr{round(sf.chi$parameter,0)} df \tabrefp{tab:GOFfishChi}.
  \item p-value\Sexpr{kPvalue(sf.chi$p.value,include.p=FALSE)} \tabrefp{tab:GOFfishChi}.
  \item $H_{0}$ is rejected because the p-value$<\alpha$.
  \item The modes of fishing do not appear to match the distribution outlined in the null hypothesis.
  \item The 95\% confidence intervals for the proportion of use of each mode is in \tabref{tab:GOFfishCIs}. From these results it is apparent that the users use the beach slightly less than expected and use charter boats slightly more than expected. The use of the pier and private boats are not different from expected.
\end{Enumerate}

\vspace{-6pt}
\begin{minipage}{\textwidth}
\textbf{R Appendix:}
\vspace{-6pt}
<<eval=FALSE, results='hide', fig.show='hide', prompt=FALSE>>=
setwd("c:/data/")
sf <- read.csv("FishingModes.csv")
<<GOFfish>>
@
\end{minipage}

\begin{table}[h]
  \caption{Observed and expected frequencies for the Goodness-of-Fit Test for modes of fishing.}
  \label{tab:GOFfishRes}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
data.frame(obs=sf.chi$observed,exp=sf.chi$expected)
@
\end{table}

\vspace{-6pt}
\begin{table}[h]
  \caption{Results from the Goodness-of-Fit Test for modes of fishing.}
  \label{tab:GOFfishChi}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
kHtest(sf.chi)
@
\end{table}

\vspace{-6pt}
\begin{table}[h]
  \caption{Observed proportions, 95\% condidence intervals for the proprtions, and expected proportions for modes of fishing.}
  \label{tab:GOFfishCIs}
  \vspace{-12pt}
<<echo=FALSE, background='white'>>=
gofCI(sf.chi,digits=3)
@
\end{table}


\subsection{Example - Mendelian Genetics II}
\vspace{-4pt}
Below are the 11-steps \sectrefp{sec:11Steps} for completing a full hypothesis test for the following situation:
\vspace{-6pt}
\begin{quote}
\textsl{Geneticists hypothesized that three of every four progeny from a cross between two parent fruitflies known to possess both a dominant and recessive allele would have red eyes. In a controlled experiment, 82 of 151 randomly selected progeny had red eyes. Test at the 1\% level if the percentage of red-eyed progeny in the population of progeny is different than what was hypothesized.}
\end{quote}
\vspace{-10pt}

<<GOFgen, echo=FALSE, results='hide', fig.show='hide', warning=FALSE>>=
obs <- c(red=82,nonred=151-82)
p.exp <- c(red=0.75,nonred=0.25)
( m.chi <- chisq.test(obs,p=p.exp,rescale.p=TRUE) )
data.frame(obs=m.chi$observed,exp=m.chi$expected)
gofCI(m.chi,digits=3)
@

\begin{Enumerate}
  \item $\alpha$=0.01.
  \item $H_{0}$:``The proportion of progeny with red eyes is 0.75'' vs. $H_{A}$:``The proportion of progeny with red eyes is NOT 0.75.''
  \item A Goodness-of-Fit Test is required because (i) a categorical variable was recorded (red eye color or not), (ii) a single group (or population) was considered in the experiment, and (iii) the observed distribution is compared to a theoretical distribution.
  \item The data appear to be experimental in that a specific cross was made and the environment in which they were raised was controlled. Progeny were randomly selected.
  \item There are more than five individuals expected in each eye level \tabrefp{tab:GOFgenRes}.
  \item The appropriate statistic is the observed frequency table in \tabref{tab:GOFgenRes}.
  \item $\chi^2$=\Sexpr{formatC(m.chi$statistic,format="f",digits=2)} with \Sexpr{round(m.chi$parameter,0)} df \tabrefp{tab:GOFgenChi}
  \item p-value\Sexpr{kPvalue(m.chi$p.value,include.p=FALSE)} \tabrefp{tab:GOFgenChi}.
  \item $H_{0}$ is rejected because the p-value $<\alpha$.
  \item The proportion of red-eyed progeny appears to be different than 0.75. Thus, the Mendelian theory is not supported by these results.
  \item From the 95\% confidence intervals in \tabref{tab:GOFgenCIs} it appears that the proportion of progeny with red eyes was between \Sexpr{formatC(gofCI(m.chi)["red","p.LCI"],format="f",digits=3)} and \Sexpr{formatC(gofCI(m.chi)["red","p.UCI"],format="f",digits=3)}, which indicates that there were many fewer red-eyed progeny than would be expected from the Mendelian theory.
\end{Enumerate}

\vspace{-6pt}
\begin{minipage}{\textwidth}
\textbf{R Appendix:}
\vspace{-4pt}
<<eval=FALSE, results='hide', fig.show='hide', prompt=FALSE>>=
<<GOFgen>>
@
\end{minipage}

\begin{table}[h]
  \caption{Observed and expected frequencies for the Goodness-of-Fit Test for the genetic cross experiment.}
  \label{tab:GOFgenRes}
  \vspace{-14pt}
<<echo=FALSE, background='white'>>=
data.frame(obs=m.chi$observed,exp=m.chi$expected)
@
\end{table}

\vspace{-6pt}
\begin{table}[h]
  \caption{Results from the Goodness-of-Fit Test for the genetic cross experiment.}
  \label{tab:GOFgenChi}
  \vspace{-14pt}
<<echo=FALSE, background='white'>>=
kHtest(m.chi)
@
\end{table}

\vspace{-6pt}
\begin{table}[h]
  \caption{Observed proportions, 95\% condidence intervals for the proprtions, and expected proportions for eye colors in the genetic cross experiment.}
  \label{tab:GOFgenCIs}
  \vspace{-14pt}
<<echo=FALSE, background='white'>>=
gofCI(m.chi,digits=3)
@
\end{table}



# Corrections {.appendix}
If you see any errors (code, typographical, or logical) please bring these to [my attention](mailto:dogle@northland.edu).
