---
layout: page
title: Calculate Sample Size
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/Explanations/")
source("../../rhelpers/rhelpers.R")
modHTML("Calc_n")
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
source("../../rhelpers/knitr_setup.R")
```

----

The required sample size to estimate a population mean within a prescribed margin-of-error (ME) and level of confidence with a given value of &sigma; (the population standard deviation) can be computed with $\big(\frac{Z^{*}\sigma}{ME}\big)^2$.

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
<li>Z<sup>*</sup> will always come from assuming a confidence interval (rather than a lower or upper bound) because of the use of "within."</li>
</ul>
</div>

For example, suppose that a researcher wanted to determine the sample size required to estimated the population mean within 10 "units" with 90% confidence assuming that &sigma;=500. In this case, ME=10 (which comes from the prescribed "within" amount) and &sigma; is obviously 500. Assuming a 90% confidence INTERVAL (i.e., 90% is in the "middle" of a standard normal distribution and 5% is in either tail) Z<sup>*</sup> is either -1.645 or +1.645 (does not make a difference as it will be squared in the sample size calculation) as computed with

```{r}
distrib(0.05,type="q")
```

Therefore, the required sample size is $\big(\frac{1.645*500}{10}\big)^2$=`r formatC((1.645*500/10)^2,format="f",digits=2)`. It is, of course, not possible to take a fraction of a sample size but note that sample size calculations are **ALWAYS** rounded up. Thus, in this example, one would take a sample size of `r ceiling((1.645*500/10)^2)` to meet the prescribed requirements.

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
<li>Sample size calculations are always <strong>rounded up</strong> to a whole number.</li>
</ul>
</div>

----
