---
title: "Review Exercise Key"
subtitle: "Hypothesis Testing Errors"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3.5
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/RE/zRevExAns/")
source("../../../rhelpers/rhelpers.R")
modHTML("HypTestingErrs")
```
```{r echo=FALSE, message=FALSE, results='hide'}
library(NCStats)
```

----

## Power Calculations 1
```{r PowerCalc1, echo=FALSE, results='hide', fig.show='hide'}
( rejreg <- distrib(0.05,mean=50,sd=20/sqrt(50),type="q") )
( pwr <- distrib(rejreg,mean=45,sd=20/sqrt(50)) )
```

The statistical power for this situation is `r formatC(pwr,format="f",digits=4)`.

### R Appendix
```{r eval=FALSE}
<<PowerCalc1>>
```

----

## Power Calculations 2
```{r PowerCalc2, echo=FALSE, results='hide', fig.show='hide'}
( rejreg <- distrib(0.10,mean=10,sd=5/sqrt(25),type="q",lower.tail=FALSE) )
( pwr <- distrib(rejreg,mean=12,sd=5/sqrt(25),lower.tail=FALSE) )
```

The statistical power for this situation is `r formatC(pwr,format="f",digits=4)`.

### R Appendix
```{r eval=FALSE}
<<PowerCalc2>>
```

----

## Power Calculations 3
```{r PowerCalc3, echo=FALSE, results='hide', fig.show='hide'}
( rejreg <- distrib(0.01,mean=75,sd=15/sqrt(30),type="q",lower.tail=FALSE) )
( pwr <- distrib(rejreg,mean=82,sd=15/sqrt(30),lower.tail=FALSE) )
```

The statistical power for this situation is `r formatC(pwr,format="f",digits=4)`.

### R Appendix
```{r eval=FALSE}
<<PowerCalc3>>
```

----
