---
title: "Answer Key"
subtitle: "2-Sample t CExmpl"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3.5
    self_contained: false
    lib_dir: libs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx/")
source("../../rhelpers/rhelpers.R")
modHTML("2Samplet_CExmpl_Key")
```

----

## Cholesterol Drug Treatments I
```{r Chol1Calc, echo=FALSE, results='hide', fig.show='hide'}
xbar1 <- 0.278; s1 <- 0.134; n1 <- 13
xbar2 <- 0.356; s2 <- 0.128; n2 <- 12
df <- n1+n2-2
sp2 <- ((n1-1)*(s1^2)+(n2-1)*(s2^2))/df
se <- sqrt(sp2*(1/n1+1/n2))
stat <- xbar1-xbar2
t <- stat/se
pv <- 2*distrib(t,distrib="t",df=df)
tstar <- distrib(0.975,type="q",distrib="t",df=df)
ci <- stat+c(-1,1)*tstar*se
```

<ol>
<li>&alpha; = 0.05.</li>
<li>H<sub>A</sub>: &mu;<sub>b</sub>-&mu;<sub>l</sub> &ne; 0 and H<sub>0</sub>: &mu;<sub>b</sub>-&mu;<sub>l</sub> = 0, where &mu; is the mean decrease in LDL of a male, b is the Befizal drug, and l is the Lipanthyl drug.</li>
<li>2-sample t-test because (i) two populations/groups are considered (Befizal and Lipanthyl drugs), (ii) a quantitative variable (decrease in LDL level) was recorded, and (iii) the samples are independent (there is no known connection between all pairs of male subjects in the two drug treatments).</li>
<li>An experimental study with random allocation (placement of subjects into the treatments) but no obvious random selection (men did not appear to be randomly selected for the experiment).</li>
<li>The assumptions are met because (i) the samples are independent (as described above), (ii) n<sub>b</sub>+n<sub>l</sub> = 13+12 = 25 &gt; 15 and the two sample distributions (shown on the handout) are not obviously strongly skewed (though it is difficult to actually see that because the sample sizes are small), and (iii) the variances appear to be equal (Levene's p-value = 0.8315 &gt; &alpha;).</li>
<li>x&#772;<sub>b</sub>-x&#772;<sub>h</sub> = `r xbar1`-`r xbar2` = `r stat`.</li>
<li>t = `r formatC(t,format="f",digits=4)` with `r df` df.</li>
<li>p-value`r kPvalue(pv,include.p=FALSE,latex=FALSE)`.</li>
<li>Do not reject H<sub>0</sub> because the p-value &lt; &alpha;.</li>
<li>It appears that the mean decrease in LDL is not significantly different between the two drug treatments.  These data do not provide a significant indication about which drug is more likely to reduce the mean LDL level in men with high cholesterol.</li>
<li>I am 95% confident that the mean decrease in LDL is between `r formatC(-1*ci[1],format="f",digits=3)` lower and `r formatC(ci[2],format="f",digits=3)` higher for men given Befizal as compared to men give Lipanthyl.  [<i>Note that the ambiguousness of this statement is consistent with not rejection the H<sub>0</sub>.</i>]</li>
</ol>

R Appendix.
```{r eval=FALSE, prompt=FALSE}
<<Chol1Calc>>
```

## Cholesterol Drug Treatments II
```{r echo=FALSE}
d <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/Cholesterol2.csv")
```
```{r eval=FALSE}
d <- read.csv("Cholesterol2.csv")
```
```{r}
d$decrease <- d$before-d$after
levenesTest(decrease~tx,data=d)
t.test(decrease~tx,data=d,var.equal=TRUE)
```

----
