---
layout: page
title: "Class Example"
subtitle: "Filtering Data In R"
author: "Derek H. Ogle"
css: "/css/modules.css"
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: false
    lib_dir: zlibs
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx")
source("../../rhelpers/rhelpers.R")
fnm <- "FilteringDataInR_CExmpl"
modHTML(fnm)
purl2(paste0(fnm,".Rmd"))
```

----

## Load Data From Webpage

Load **Fire.csv** into an R data.frame called `firedf`. *Open your script and copy your code from last class period.*
```{r echo=FALSE}
firedf <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/Fire.csv")
```
```{r message=FALSE}
library(NCStats)
```
```{r eval=FALSE}
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx")
firedf <- read.csv("Fire.csv")
```
```{r}
str(firedf)
headtail(firedf)
```

<br>

----

## Examining Single Variables

* Examine the stand type (i.e., `sttype`) variable.
```{r include=FALSE}
firedf$sttype
```

* Examine the litter depth (i.e., `litdep`) variable.
```{r include=FALSE}
firedf$litdep
```

<br>

----

## Filtering Data Frames
* Isolate just the `deciduous` stand types.
```{r include=FALSE}
decid <- filterD(firedf,sttype=="d")
str(decid)
headtail(decid)
```

* Isolate the stands with a litter depth less than 2 cm.
```{r include=FALSE}
lt2 <- filterD(firedf,litdep<2)
headtail(lt2)
```

* Isolate the stand types that are either coniferous or mixed-coniferous.
```{r include=FALSE}
conif <- filterD(firedf,sttype %in% c("c","mc"))
str(conif)
headtail(conif)
```

* Isolate stands that were conferous (not including mixed-coniferous) and had a litter depth greater than 2 cm.
```{r include=FALSE}
con_gt2 <- filterD(firedf,sttype=="c",litdep>2)
str(con_gt2)
con_gt2
```

* Isolate all stands that had a litter depth between 1 and 2 cm.
```{r include=FALSE}
LDbw1n2 <- filterD(firedf,litdep>1,litdep<2)
headtail(LDbw1n2)
```

----
