---
layout: page
title: "Class Example"
subtitle: "Getting Data Into R"
author: "Derek H. Ogle"
css: "/css/modules.css"
output:
  html_document:
    fig_width: 3.5
    fig_height: 3.5
    self_contained: false
    lib_dir: zlibs
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx")
source("../../rhelpers/rhelpers.R")
fnm <- "GettingDataIntoR_CExmpl"
modHTML(fnm)
purl2(paste0(fnm,".Rmd"))
```

```{r echo=FALSE, results='hide', message=FALSE}
fnm <- "GettingDataIntoR"
source("../../rhelpers/knitr_setup.R")
```

----

## Always First Command
**EVERY** RStudio session for this class should begin with the following code.
```{r results='hide', message=FALSE, warning=FALSE, prompt=FALSE}
library(NCStats)
```

<br>

----

## Load Data From Webpage

1. Load **fire.csv** into an R data.frame called `firedf`. 

```{r eval=FALSE, echo=FALSE}
library(NCStats)
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx")
firedf <- read.csv("Iris.csv")
str(firedf)
headtail(firedf)
```

<br>

----

## Enter Own Data

1. Create an R data.frame (by first creating a CSV file) that contains the following three variables for each course you are taking this semester: name of your professor (e.g., "Ogle"), course abbreviation (e.g., "MTH107"), and number of credits (e.g., "4").

----
