---
layout: page
title: Class Example
subtitle: Linear Regression
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CEx/")
source("../../rhelpers/rhelpers.R")
modHTML("LinearRegression_CExmpl")
```

----

## Climate Change Data

Climate researchers examined the relationship between global temperature anomaly and the concentration of CO<sub>2</sub> in the atmosphere. Temperature anomaly data was recorded as the Global Land-Ocean Temperature Index from the Goddard Institute of Space Studies (GISTEMP). It is reported in units of 1/100 of a degree centigrade increase above the 1950-1980 mean. The CO<sub>2</sub> data are from The Earth System Research Laboratory of the National Oceanic and Atmospheric Administration (NOAA). Specifically, these data are a record of annual mean atmospheric <sub>2</sub> concentration at Mauna Loa Observatory, Hawaii, and constitute the longest continuous record of atmospheric <sub>2</sub> concentration. This remote location at high altitude in Hawaii was chosen because it is relatively unaffected by any local emissions and so is representative of the global concentration of a well-mixed gas like <sub>2</sub>. These observations were started by C. David Keeling of the Scripps Institution of Oceanography in March of 1958 and are often referred to as the Keeling Curve. Data are reported as a dry mole fraction defined as the number of molecules of carbon dioxide divided by the number of molecules of dry air multiplied by one million (ppm). Our goal here is to determine if the variability in the temperature anomaly records can be reasonably explained by the CO<sub>2</sub> values in the same year.

```{r echo=FALSE, results="hide", fig.height=3.5, fig.width=3.5, fig.show="hold"}
library(NCStats)
df <- read.csv("GSI_data.csv")
lm1 <- lm(Temp~CO2,data=df)
cf1 <- coef(lm1)
res1 <- paste0("Y=",formatC(cf1[1],format="f",digits=2),"+",
              formatC(cf1[2],format="f",digits=2),"*X\nr^2=",
              formatC(rSquared(lm1),format="f",digits=2))
lm2 <- lm(CO2~Temp,data=df)
cf2 <- coef(lm2)
res2 <- paste0("Y=",formatC(cf2[1],format="f",digits=2),"+",
              formatC(cf2[2],format="f",digits=2),"*X\nr^2=",
              formatC(rSquared(lm2),format="f",digits=2))

par(mar=c(3,3,0.7,0.7),mgp=c(1.9,0.5,0),tcl=-0.2)
fitPlot(lm1,xlab="CO2 in Atmosphere (ppm)",ylab="Temperature Anomaly (1/100C)")
legend("topleft",legend=res1,bty="n")
fitPlot(lm2,ylab="CO2 in Atmosphere (ppm)",xlab="Temperature Anomaly (1/100C)")
legend("topleft",legend=res2,bty="n")
```

1. What is the response variable? [*Hint: Read the rest of the questions before answering this question.*]
1. What is the explanatory variable?
1. In terms of the variables of this problem, what is the equation of the best-fit line?
1. In terms of the variables of this problem, interpret the value of the slope.
1. In terms of the variables of this problem, interpret the value of the intercept.
1. What is the predicted temperature anomoly if the CO2 is 360 ppm?
1. What is the predicted temperature anomoly if the CO2 is 250 ppm?
1. What is the residual if the temperature anomoly is 40 and the CO2 is 380 ppm?
1. What proportion of the variability in temperature anomaly is explained by knowing the CO2 amount?
1. What is the correlation coefficient between temperature anomaly and CO2 amount?
1. How much will the predicted temperature anomaly change if the CO2 amount increased by 20 ppm?
1. What aspect of this regression analysis concerns you? [*Hint: consider the regression assumptions*]?

----
