---
title: "Answer Key"
subtitle: "Normal Distributions CE 1"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/CE/1_CE_Keys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_NormalDist_CE1")
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
```

----

## Normal Distribution Characteristics I

1. Using `snorm()`
    1. The whole distributions shifts to the right.
    1. The distribution becomes wider (more dispersed).
1. Below
    1. $\mu$=75, $\sigma$=10
    1. $\mu$=5500, $\sigma$=600
    1. $\mu$=0, $\sigma$=1

----

## Hand Calculations I
For X~N(75,10) 

1. 97.5%
1. 0.15%
1. 68%
1. 81.5%
1. Less than 55.
1. Between X=55 and 95.
1. Greater than X=95.

----

<div class="alert alert-warning">
<strong>Note:</strong>
<ul>
<li>If it is a reverse question (given a percentage/proportion and asked to find a value of the variable) then you must include <code>type="q"</code> in <code>distrib()</code>.</li>
<li>If it is a "right-of" question then you must include <code>lower.tail=FALSE</code> in <code>distrib()</code>.</li>
<li>All "between" questions require a three-step process with <code>distrib()</code> to answer. If it is a forward question then <code>distrib()</code> is used to find the areas to the left of the two given values and then those two areas are subtracted. If it is a reverse question then the area between must be converted to a left-of area and a right-of area which are then separately put into <code>distrib()</code> to compute two values (which are the final answer).</li>
</ul>
</div>

## Carpenter Ants
#### Top questions
1. A nest
1. Number of Carpenter Ants in a nest
1. Discrete quantitative
1. $\mu$=1400
1. $\sigma$=300

#### Bottom questions
1. (a) forward, right-of; (b) `r formatC(distrib(1900,mean=1400,sd=300,lower.tail=FALSE)*100,format="f",digits=2)`%.
1. (a) reverse, right-of; (b) `r formatC(distrib(0.15,mean=1400,sd=300,type="q",lower.tail=FALSE),format="f",digits=0)` ants.
1. (a) reverse, left-of; (b) `r formatC(distrib(0.33,mean=1400,sd=300,type="q"),format="f",digits=0)` ants.
1. (a) forward, between; (b) `r formatC((distrib(1900,mean=1400,sd=300)-distrib(700,mean=1400,sd=300))*100,format="f",digits=2)`%.
1. (a) forward, left-of; (b) `r formatC(distrib(300,mean=1400,sd=300)*100,format="f",digits=3)`%.
1. (a) reverse, right-of; (b) `r formatC(distrib(0.05,mean=1400,sd=300,type="q",lower.tail=FALSE),format="f",digits=0)` ants.
1. (a) reverse, between; (b) Between `r formatC(distrib(0.10,mean=1400,sd=300,type="q"),format="f",digits=0)` and  `r formatC(distrib(0.10,mean=1400,sd=300,type="q",lower.tail=FALSE),format="f",digits=0)` ants.

R Appendix.
```{r eval=FALSE, prompt=FALSE}
distrib(1900,mean=1400,sd=300,lower.tail=FALSE)*100
distrib(0.15,mean=1400,sd=300,type="q",lower.tail=FALSE)
distrib(0.33,mean=1400,sd=300,type="q")
ab <- distrib(1900,mean=1400,sd=300)
a <- distrib(700,mean=1400,sd=300)
(ab-a)*100
distrib(300,mean=1400,sd=300)*100
distrib(0.05,mean=1400,sd=300,type="q",lower.tail=FALSE)
distrib(0.10,mean=1400,sd=300,type="q")
distrib(0.10,mean=1400,sd=300,type="q",lower.tail=FALSE)
```

----
