---
title: "Answer Key"
subtitle: "Summaries for One Quantitative Variable CE"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
---

```{r echo=FALSE, eval=FALSE}
## Renders an appropriate HTML file for the webpage
fnm <- "UEDAQuant1_CE_Keys"
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/CE/Keys")
source("../../../rhelpers/rhelpers.R")
modHTML(fnm)
## And moves it to make it available to students
file.rename(from=paste0(fnm,".html"),to=paste0("../",fnm,".html"))
dir.create(paste0("../",fnm,"_files"),showWarnings=FALSE)
file.copy(from=paste0(fnm,"_files"),to=paste0("../"),recursive=TRUE)
```

```{r echo=FALSE, results='hide', message=FALSE}
library(NCStats)
source("../../../rhelpers/knitr_setup.R")
library(captioner)
tbls <- captioner(prefix="Table")
figs <- captioner(prefix="Figure")
tbls(name="Brain1","Summary statistics for brain weight (g).")
tbls(name="Brain2","Summary statistics for brain weight (g) separated by age group.")
figs(name="Brain1","Histogram of brain weight (g).")
figs(name="Brain2","Histograms of brain weight (g) separated by age group.")
```

----

## Hand Calculations

<ol>
<li>Shown below</li>
```{r}
sdCalc(c(18,28,25,21,16,24))
```
<li>Shown above</li>
<li>Shown below</li>
```{r}
iqrCalc(c(4,54,16,85,52,29,24,71,61,60,2))
```
<li>Shown above</li>
<li>Shown below</li>
```{r}
iqrCalc(c(93,81,34,5,54,84,54,13,1,35,79,63,97,71))
```

<li>Shown above</li>
<li>Range is 1 to 97.</li>
</ol>

----

## Histograms I

1. An individual is a state.
1. The variable is the mean commute time for indivuals 16-years and older in states of the U.S.
1. Mean Commute time (mins) is a quantitative, continuous variable.
1. 51
1. 2
1. 25
1. 26-28

----

## Brain Weights
```{r echo=FALSE}
d <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/BrainHead.csv")
```

<ol>
<li>The histogram of brain weights is in `r figs("Brain1",display="cite")`.</li>
```{r BrainHist1, echo=FALSE, fig.width=3, fig.height=3, par1=TRUE}
hist(~brain.weight,data=d,xlab="Brain Weight (g)")
```

`r figs("Brain1")`

<li>The summary statistics for brain weights is in `r tbls("Brain1",display="cite")`.</li>

`r tbls("Brain1")`

```{r BrainSum1, echo=FALSE, background="white"}
Summarize(~brain.weight,data=d,digits=1)
```

<li>The histogram of brain weights separated by age group is in `r figs("Brain2",display="cite")`.</li>
```{r BrainHist2, echo=FALSE, fig.width=6, fig.height=3, par1=TRUE}
hist(brain.weight~age.group,data=d,xlab="Brain Weight (g)")
```

`r figs("Brain2")`

<li>The summary statistics of brain weights separate by age groups is in `r tbls("Brain2",display="cite")`.</li>

`r tbls("Brain2")`

```{r BrainSum2, echo=FALSE, background="white"}
Summarize(brain.weight~age.group,data=d,digits=1)
```
</ol>

R Appendix.
```{r eval=FALSE, prompt=FALSE}
d <- read.csv("data/BrainHead.csv")
<<BrainHist1>>
<<BrainSum1>>
<<BrainHist2>>
<<BrainSum2>>
```

----
