---
title: "Review Exercise Key"
subtitle: "Summaries for One Quantitative Variable"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3.5
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/zRevExAns/")
source("../../rhelpers/rhelpers.R")
modHTML("UEDAQuant1_Graphical")
```
```{r echo=FALSE, results="hide"}
library(captioner)
figs <- captioner(prefix="Figure")
figs(name="CPHist","Histogram of the creatine phosphokinase concentrations in 36 male volunteers.")
figs(name="POLLNHist","Histogram of the carbon monoxide levels arising from the oil refinery stack.")
```

## Creatine Phosphate Concentrations

The histogram is in `r figs("CPHist",display="cite")`.

```{r CPHist, echo=FALSE, comment=""}
cp <- c(121,82,100,151,68,58,95,145,64,119,104,110,113,118,203,62,83,67,201,
101,163,84,57,139,60,78,94,93,92,110,25,123,70,48,95,42)
hist(~cp,xlab="Creatine Phosphate Concentration (ppm)")
```

`r figs("CPHist")`

### R Code Appendix
```
library(NCStats)
df <- read.csv("data/CreatinePhosphate.csv")
hist(~cp,data=df,xlab="Creatine Phosphate Concentration (ppm)")
```

----

## Air Pollution

The histogram is in `r figs("POLLNHist",display="cite")`.

```{r POLLNHist, echo=FALSE, comment=""}
polln <- c(30,30,34,36,37,38,40,42,43,43,45,52,55,58,58,58,59,63,63,71,75,85,86,86,99,102,102,141,153,261,21)
hist(~polln,xlab="Carbon Monoxide Levels (ppm)")
```

`r figs("POLLNHist")`

### R Code Appendix
```
library(NCStats)
df <- read.csv("data/Polln.csv")
hist(~polln,data=df,xlab="Carbon Monoxide Levels (ppm))
```

----
