---
title: "Review Exercise Key"
subtitle: "Summaries for One Quantitative Variable"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3.5
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/zRevExAns/")
source("../../rhelpers/rhelpers.R")
modHTML("UEDAQuant1_Extras")
```

## Brule River Gauge Heights

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
hts <- c(1.56,1.54,1.54,1.57,1.58,1.61,1.60,1.69,
         1.99,2.11,1.98,1.76,1.69,1.99,1.86,1.53)
iqrCalc(hts)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(hts)
```

### R Code Appendix
```
library(NCStats)
df <- read.csv("data/BruleRiver.csv")
Summarize(~gauge,data=df)
```

----

## Population Density in Wisconsin Counties

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
dens <- c(429.0,67.8,52.1,97.4,57.9,354.9,16.2,19.1,127.0,27.6,10.2,54.6,28.8,30.1,20.2)
iqrCalc(dens)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(dens)
```

### R Code Appendix
```
library(NCStats)
df <- read.csv("data/WIDensity.csv")
Summarize(~dens,data=df)
```

----
