---
title: "Review Exercise Key"
subtitle: "Summaries for One Quantitative Variable"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3.5
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH107/modules/zRevExAns/")
source("../../rhelpers/rhelpers.R")
modHTML("UEDAQuant1_Numerical")
```

## Number of States Visited

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
states <- c(8, 3, 17, 15, 4, 19)
iqrCalc(states)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(states)
```

----

## Home Range of Red Kangaroos

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
kang <- c(258, 310, 560, 470, 502)
iqrCalc(kang)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(kang)
```

----

## Creatine Phosphate Concentrations

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
cp <- c(121,82,100,151,68,58,95,145,64,119,104,110,113,118,203,62,83,67,201,
101,163,84,57,139,60,78,94,93,92,110,25,123,70,48,95,42)
iqrCalc(cp)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(cp)
```

### R Code Appendix
```
library(NCStats)
df <- read.csv("data/CreatinePhosphate.csv")
Summarize(~cp,data=df)
```

----

## Air Pollution

The calculation of the median and IQR is shown below.
```{r echo=FALSE, comment=""}
polln <- c(30,30,34,36,37,38,40,42,43,43,45,52,55,58,58,58,59,63,63,71,75,85,86,86,99,102,102,141,153,261,21)
iqrCalc(polln)
```

The calculation of the mean and standard deviation is shown below.
```{r echo=FALSE, comment=""}
sdCalc(polln)
```

# R Code Appendix
```
library(NCStats)
df <- read.csv("data/Polln.csv")
Summarize(~polln,data=df)
```

----
